spring:
  application:
    name: tican-lib-autoconfigure-interceptors

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: docker

---
spring:
  config:
    activate:
      on-profile: k8s
