apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-server-pvc
  labels:
    app: auth-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
