apiVersion: v1
kind: Service
metadata:
  name: auth-server-svc
  labels:
    app: auth-server-svc
spec:
  type: ClusterIP
  selector:
    app: auth-server-pod
  ports:
    - port: 6002
      targetPort: 6002
