apiVersion: v1
kind: Service
metadata:
  name: auth-server-nodeport
  labels:
    app: auth-server-nodeport
spec:
  type: NodePort
  ports:
    - port: 6002
      nodePort: 31002
  selector:
    app: auth-server-pod
