insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 1, 'Dados Cadastrais PF', 1, 'CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 1, 'Dados Cadastrais PF', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 2, 'Informações complementares PF', 1, 'CUSTOMERS_PERSONAL_ADITTIONALINFO_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 2, 'Informações complementares PF', 0, 'RESOURCES_READ', 'false', 'Por recurso');


insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 3, 'Dados Cadastrais PJ', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 3, 'Dados Cadastrais PJ', 1, 'CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ', 'true', 'Por recurso');

insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 4, 'Informações complementares PJ', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) 
VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CUSTOMER'), 1, 'Cadastro', 4, 'Informações complementares PJ', 1, 'CUSTOMERS_BUSINESS_ADITTIONALINFO_READ', 'true', 'Por recurso');


insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 1, 'Saldos', 1, 'ACCOUNTS_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 1, 'Saldos', 2, 'ACCOUNTS_BALANCES_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 1, 'Saldos', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 2, 'Limites', 1, 'ACCOUNTS_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 2, 'Limites', 2, 'ACCOUNTS_OVERDRAFT_LIMITS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 2, 'Limites', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 3, 'Extratos', 1, 'ACCOUNTS_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 3, 'Extratos', 2, 'ACCOUNTS_TRANSACTIONS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'ACCOUNT'), 2, 'Contas', 3, 'Extratos', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 1, 'Limites', 1, 'CREDIT_CARDS_ACCOUNTS_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 1, 'Limites', 2, 'CREDIT_CARDS_ACCOUNTS_LIMITS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 1, 'Limites', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 2, 'Transações', 1, 'CREDIT_CARDS_ACCOUNTS_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 2, 'Transações', 2, 'CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 2, 'Transações', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 3, 'Faturas', 1, 'CREDIT_CARDS_ACCOUNTS_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 3, 'Faturas', 2, 'CREDIT_CARDS_ACCOUNTS_BILLS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 3, 'Faturas', 3, 'CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ', 'true', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_CARD_ACCOUNT'), 3, 'Cartão de Crédito', 3, 'Faturas', 0, 'RESOURCES_READ', 'false', 'Por recurso');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'LOAN'), 4, 'Operações de Crédito', 1, 'Dados do Contrato', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'LOAN'), 4, 'Operações de Crédito', 1, 'Dados do Contrato', 1, 'LOANS_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'LOAN'), 4, 'Operações de Crédito', 1, 'Dados do Contrato', 2, 'LOANS_WARRANTIES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'LOAN'), 4, 'Operações de Crédito', 1, 'Dados do Contrato', 3, 'LOANS_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'LOAN'), 4, 'Operações de Crédito', 1, 'Dados do Contrato', 4, 'LOANS_PAYMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FINANCING'), 4, 'Operações de Crédito', 2, 'Dados do Contrato', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FINANCING'), 4, 'Operações de Crédito', 2, 'Dados do Contrato', 1, 'FINANCINGS_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FINANCING'), 4, 'Operações de Crédito', 2, 'Dados do Contrato', 2, 'FINANCINGS_WARRANTIES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FINANCING'), 4, 'Operações de Crédito', 2, 'Dados do Contrato', 3, 'FINANCINGS_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FINANCING'), 4, 'Operações de Crédito', 2, 'Dados do Contrato', 4, 'FINANCINGS_PAYMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'UNARRANGED_ACCOUNT_OVERDRAFT'), 4, 'Operações de Crédito', 3, 'Dados do Contrato', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'UNARRANGED_ACCOUNT_OVERDRAFT'), 4, 'Operações de Crédito', 3, 'Dados do Contrato', 1, 'UNARRANGED_ACCOUNTS_OVERDRAFT_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'UNARRANGED_ACCOUNT_OVERDRAFT'), 4, 'Operações de Crédito', 3, 'Dados do Contrato', 2, 'UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'UNARRANGED_ACCOUNT_OVERDRAFT'), 4, 'Operações de Crédito', 3, 'Dados do Contrato', 3, 'UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_RE', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'UNARRANGED_ACCOUNT_OVERDRAFT'), 4, 'Operações de Crédito', 3, 'Dados do Contrato', 4, 'UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'INVOICE_FINANCING'), 4, 'Operações de Crédito', 4, 'Dados do Contrato', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'INVOICE_FINANCING'), 4, 'Operações de Crédito', 4, 'Dados do Contrato', 1, 'INVOICE_FINANCINGS_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'INVOICE_FINANCING'), 4, 'Operações de Crédito', 4, 'Dados do Contrato', 2, 'INVOICE_FINANCINGS_WARRANTIES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'INVOICE_FINANCING'), 4, 'Operações de Crédito', 4, 'Dados do Contrato', 3, 'INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'INVOICE_FINANCING'), 4, 'Operações de Crédito', 4, 'Dados do Contrato', 4, 'INVOICE_FINANCINGS_PAYMENTS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'BANK_FIXED_INCOME'), 5, 'Investimento', 1, 'Dados da Operação', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'BANK_FIXED_INCOME'), 5, 'Investimento', 1, 'Dados da Operação', 1, 'BANK_FIXED_INCOMES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_FIXED_INCOME'), 5, 'Investimento', 2, 'Dados da Operação', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'CREDIT_FIXED_INCOME'), 5, 'Investimento', 2, 'Dados da Operação', 1, 'CREDIT_FIXED_INCOMES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FUND'), 5, 'Investimento', 3, 'Dados da Operação', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'FUND'), 5, 'Investimento', 3, 'Dados da Operação', 1, 'FUNDS_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'VARIABLE_INCOME'), 5, 'Investimento', 4, 'Dados da Operação', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'VARIABLE_INCOME'), 5, 'Investimento', 4, 'Dados da Operação', 1, 'VARIABLE_INCOMES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'TREASURE_TITLE'), 5, 'Investimento', 5, 'Dados da Operação', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'TREASURE_TITLE'), 5, 'Investimento', 5, 'Dados da Operação', 1, 'TREASURE_TITLES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'EXCHANGE'), 6, 'Câmbio', 1, 'Listar', 1, 'EXCHANGES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'EXCHANGE'), 6, 'Câmbio', 1, 'Listar', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'EXCHANGE'), 6, 'Câmbio', 2, 'Detalhes da Operação', 1, 'EXCHANGES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'EXCHANGE'), 6, 'Câmbio', 2, 'Detalhes da Operação', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'EXCHANGE'), 6, 'Câmbio', 3, 'Eventos', 1, 'EXCHANGES_READ', 'true', 'Por agrupamento de produtos');
insert into ofb.resources_permissions (resourcetypeid, permissioncategoryid, permissioncategory, permissioneventgroupid, permissioncategorygroup, permissioncategoryorder, permission, ispermissionevent, permissiongrouping) VALUES((SELECT RESOURCETYPEID FROM OFB.RESOURCES_TYPES WHERE TYPE = 'EXCHANGE'), 6, 'Câmbio', 3, 'Eventos', 0, 'RESOURCES_READ', 'false', 'Por agrupamento de produtos');
/
COMMIT;
/
