USE OFB;

CREATE TABLE `ofb_audit` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `XTICKETID` varchar(20) DEFAULT 'not informed',
  `XFAPIINTERACTIONID` varchar(100) DEFAULT 'not informed',
  `REQUESTTIME` varchar(200) DEFAULT 'not informed',
  `REQUESTURI` varchar(400) DEFAULT 'not informed',
  `REQUESTMETHOD` varchar(100) DEFAULT 'not informed',
  `REQUESTUSERNAME` varchar(100) DEFAULT 'not informed',
  `PAYLOAD` varchar(6000) DEFAULT 'not informed',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=991030869 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ofb_audit_authorization_consents` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `XTICKETID` varchar(20) NOT NULL,
  `XFAPIINTERACTIONID` varchar(100) NOT NULL,
  `CONSENTID` varchar(256) NOT NULL,
  `CONSENTREQUESTDATE` timestamp NOT NULL,
  `CONSENTAPPROVEDDATE` timestamp NOT NULL,
  `PAYLOAD` varchar(6000) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=102205910 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ofb_audit_cancellation_consents` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `XTICKETID` varchar(20) NOT NULL,
  `XFAPIINTERACTIONID` varchar(100) NOT NULL,
  `CONSENTID` varchar(256) NOT NULL,
  `CONSENTREQUESTDATE` timestamp NOT NULL,
  `CONSENTCANCELDATE` timestamp NOT NULL,
  `REASON` varchar(500) NOT NULL,
  `PAYLOAD` varchar(6000) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=971544199 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `ofb_audit_revoked_consents` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `XTICKETID` varchar(20) NOT NULL,
  `XFAPIINTERACTIONID` varchar(100) NOT NULL,
  `CONSENTID` varchar(256) NOT NULL,
  `CONSENTREQUESTDATE` timestamp NOT NULL,
  `CONSENTREVOKEDDATE` timestamp NOT NULL,
  `REASON` varchar(500) NOT NULL,
  `PAYLOAD` varchar(6000) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=971544199 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ofb_audit_extends_consents` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `XTICKETID` varchar(20) NOT NULL,
  `XFAPIINTERACTIONID` varchar(100) NOT NULL,
  `CONSENTID` varchar(256) NOT NULL,
  `CONSENTREQUESTDATE` timestamp NOT NULL,
  `CONSENTEXTENDSDATE` timestamp NOT NULL,
  `PAYLOAD` varchar(6000) NOT NULL,
  PRIMARY KEY (`ID`)
);
