apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-rabbit-pvc
  labels:
    app: mq-rabbit-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
      
