apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oauth2-users-business-services
  labels:
    app: oauth2-users-business-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-users-business-pod
  template:
    metadata:
      name: oauth2-users-business-pod
      labels:
        app: oauth2-users-business-pod
    spec:
      containers:
        - name: oauth2-users-business-container
          image: fras200627/oauth2-users-business:1.0.0
          ports:
            - containerPort: 6005
          envFrom:
            - configMapRef:
                name: config-map-defaults
            - configMapRef:
                name: oauth2-users-business-cmap  
          volumeMounts:
            - name: oauth2-users-business-persist
              mountPath: /default/oauth2-users-business-pvc
      volumes:
        - name: oauth2-users-business-persist
          persistentVolumeClaim:
            claimName: oauth2-users-business-pvc
  serviceName: oauth2-users-business-services-stateful
    