apiVersion: v1
kind: Service
metadata:
  name: oauth2-users-business-nodeport
  labels:
    app: oauth2-users-business-nodeport
spec:
  type: NodePort
  ports:
    - port: 6005
      nodePort: 31005
  selector:
    app: oauth2-users-business-pod
