# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-oracle-pvc
  labels:
    app: db-oracle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      
