spring:
  application:
    name: ofb-lib-autoconfigure-security
jwt:
  issuer: banco-tcn-openfinance-brasil
  private:
    key: classpath:keystore/app.private.key
  public:
    key: classpath:keystore/app.public.key

---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: docker
---
spring:
  config:
    activate:
      on-profile: k8s
