spring:
  application:
    name: ofb-consents
  jpa:
    properties:
      hibernate:
        format_sql: true    
    show-sql: ${API_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${API_HIBERNATE_DDL_AUTO:none}
server:
  error:
    include-stacktrace: never

jwt:
  issuer: banco-tcn-openfinance-brasil
  private:
    key: classpath:keystore/app.private.key
  public:
    key: classpath:keystore/app.public.key

# Custom properties
app:
  consents:
    organization: 'Banco TCN - OpenFinance Brasil'
    consent-id-urn-use: 'bancotcn'
    validate:
      check-if-consent-already-exists: false
      execute-throw-immediately: false
  paths:
    clients:
      registered-clients: 'http://localhost:3001/ofb-clients-business-api/registered/clients'

  listOfServers: #server item: id, description, url
    - 0, 'OFB Server at LOCAL execution', http://localhost/3000
    - 1, 'OFB Server at DOCKER execution', http://localhost/5000
    - 2, 'OFB Server at K8S execution', http://localhost/7000
eureka:
  instance:
    hostname: ${DISCOVERY_SERVICES_APP_NAME:ofb-discovery-services}
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
resilience4j:
  circuitBreaker:
    instances:
      authServerDomain:
        waitDurationInOpenState: 50s
        minimumNumberOfCalls: 2
        slidingWindowSize: 3
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

# Swagger page: http://localhost:3031/swagger-ui
springdoc:
  api-docs:
    enabled: true
  packagesToScan: com.ofb
  pathsToMatch: /**
  swagger-ui:
    enabled: true
    path: /swagger-ui
    disable-swagger-default-url: true
    show-common-extensions: true
    show-extensions: true
    operationsSorter: alpha
    tagsSorter: alpha

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: OFB_USER
    password: ofb
    driver-class-name: oracle.jdbc.OracleDriver
    serverTimezone: America/Sao_Paulo
    useSSL: false
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    type: com.zaxxer.hikari.HikariDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
amqp:
  audit_services:
    audit_queue: ${API_CONSENTS_ADMIN_QUEUE:ofb.consents.admin.queue}
    audit_exchange: ${API_CONSENTS_ADMIN_EX:ofb.consents.admin.ex}
    audit_dlq: ${API_CONSENTS_ADMIN_DLQ:ofb.consents.admin.dlq}
    audit_dlx: ${API_CONSENTS_ADMIN_DLX:ofb.consents.admin.dlx}
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3031 # set to "0" if you want eureka-server to determine a port dynamically
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: OFB_USER
    password: ofb
    driver-class-name: oracle.jdbc.OracleDriver
    serverTimezone: America/Sao_Paulo
    useSSL: false
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    type: com.zaxxer.hikari.HikariDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.1:3000/eureka
amqp:
  audit_services:
    audit_queue: ${API_AMQP_AUDIT_QUEUE:ofb.audit.admin.queue}
    audit_exchange: ${API_AMQP_AUDIT_EX:ofb.audit.admin.ex}
    audit_dlq: ${API_AMQP_AUDIT_DLQ:ofb.audit.admin.dlq}
    audit_dlx: ${API_AMQP_AUDIT_DLX:ofb.audit.admin.dlx}
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3031 # set to "0" if you want eureka-server to determine a port dynamically
---
spring:
  config:
    activate:
      on-profile: k8s
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:ofb}
    password: ${RABBITMQ_DEFAULT_PASS:ofb}
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: OFB_USER
    password: ofb
    driver-class-name: oracle.jdbc.OracleDriver
    serverTimezone: America/Sao_Paulo
    useSSL: false
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    type: com.zaxxer.hikari.HikariDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.152.183.103:3000/eureka
amqp:
  audit_services:
    audit_queue: ${API_AMQP_AUDIT_QUEUE:ofb.audit.admin.queue}
    audit_exchange: ${API_AMQP_AUDIT_EX:ofb.audit.admin.ex}
    audit_dlq: ${API_AMQP_AUDIT_DLQ:ofb.audit.admin.dlq}
    audit_dlx: ${API_AMQP_AUDIT_DLX:ofb.audit.admin.dlx}
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3031 # set to "0" if you want eureka-server to determine a port dynamically
