apiVersion: v1
kind: Service
metadata:
  name: tican-oauth2-clients-domain-nodeport
  labels:
    app: tican-oauth2-clients-domain-nodeport
spec:
  type: NodePort
  clusterIP: 10.152.183.123
  ports:
    - port: 3061
      nodePort: 30061
  selector:
    app: tican-oauth2-clients-domain-pod

