apiVersion: v1
kind: Service
metadata:
  name: oauth2-users-domain-nodeport
  labels:
    app: oauth2-users-domain-nodeport
spec:
  type: NodePort
  ports:
    - port: 6004
      nodePort: 31004
  selector:
    app: oauth2-users-domain-pod
