spring:
  application:
    name: ${AUTHENTICATION_SERVER_APP_NAME:auth-server-svc}
  session:
    store-type: jdbc
  security:
    filter:
      dispatcher-types: request
    auth:
      jks:
        keypass: 123456
        storepass: 123456
        alias: tican
        path: keystore/tican.jks
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: ${API_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${API_HIBERNATE_DDL_AUTO:none}
server:
  error:
    include-stacktrace: never

jwt:
  issuer: banco-tcn-openfinance-brasil

# Custom properties
app:
  listOfServers: #server item: id, description, url
    - 0, 'Tican Server at LOCAL execution', http://localhost/3000
    - 1, 'Tican Server at DOCKER execution', http://localhost/3000
    - 2, 'Tican Server at K8S execution', http://localhost/3000
  environment: local
  app_info:
    name: Tican Services
    title: Tican Services Engine - Authentication Server
    version: 1.0.0
    build: v.02_2025

eureka:
  instance:
    hostname: ${DISCOVERY_SERVICES_APP_NAME:ofb-discovery-services}
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitBreaker:
    instances:
      authServerDomain:
        waitDurationInOpenState: 50s
        minimumNumberOfCalls: 2
        slidingWindowSize: 3

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

# Swagger page: http://localhost:3031/swagger-ui
springdoc:
  api-docs:
    enabled: true
  packagesToScan: com.tican
  pathsToMatch: /**
  swagger-ui:
    enabled: true
    path: /swagger-ui
    disable-swagger-default-url: true
    show-common-extensions: true
    show-extensions: true
    operationsSorter: alpha
    tagsSorter: alpha

---
spring:
  config:
    activate:
      on-profile: local
  security:
    auth:
      provider-uri: http://localhost:3001/auth-server-svc
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PWD:root}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
amqp:
  audit_services:
    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}
    
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3032 # set to "0" if you want eureka-server to determine a port dynamically
---
spring:
  config:
    activate:
      on-profile: docker
  security:
    auth:
      provider-uri: http://10.0.1.2:3001/auth-server-svc
  datasource:
    url: jdbc:mysql://10.0.1.100:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PWD:tican}
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.1:3000/eureka
amqp:
  audit_services:
    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}
    
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3032 # set to "0" if you want eureka-server to determine a port dynamically
---
spring:
  config:
    activate:
      on-profile: k8s
  security:
    auth:
      provider-uri: http://10.152.183.107:3001/auth-server-svc
  datasource:
    url: jdbc:mysql://10.152.183.209:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PWD:root}
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.152.183.103:3000/eureka
amqp:
  audit_services:
    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}
    
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3032 # set to "0" if you want eureka-server to determine a port dynamically