spring:
  application:
    name: ${API_GATEWAY_APP_NAME:ofb-api-gateway}
  cloud:
    discovery:
      enable: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  main:
    web-application-type: reactive # Required for OpenAPI x Cloud.Gateway compatibility
server:
  error:
    include-stacktrace: never
# Custom properties
app:
  listOfServers: #server item: id, description, url
    - 0, 'OFB Server at LOCAL execution', http://localhost/3000
    - 1, 'OFB Server at DOCKER execution', http://localhost/5000
    - 2, 'OFB Server at K8S execution', http://localhost/7000

eureka:
  instance:
    hostname: ${DISCOVERY_SERVICES_APP_NAME:ofb-discovery-services}
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

# Swagger page: not work with spring.api.gateway
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
amqp:
  audit_services:
    queue: ofb.audit.queue
    exchange: ofb.audit.ex
    dlq: ofb.audit.dlq
    dlx: ofb.audit.dlx
  ofb_consents_cancel:
    queue: ofb.consents.cancel.queue
    exchange: ofb.consents.cancel.ex
    dlq: ofb.consents.cancel.dlq
    dlx: ofb.consents.cancel.dlx
  ofb_consents_authorization:
    queue: ofb.consents.auth.queue
    exchange: ofb.consents.auth.ex
    dlq: ofb.consents.authn.dlq
    dlx: ofb.consents.auth.dlx
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.1:3000/eureka
amqp:
  audit_services:
    queue: ofb.audit.queue
    exchange: ofb.audit.ex
    dlq: ofb.audit.dlq
    dlx: ofb.audit.dlx
  ofb_consents_cancel:
    queue: ofb.consents.cancel.queue
    exchange: ofb.consents.cancel.ex
    dlq: ofb.consents.cancel.dlq
    dlx: ofb.consents.cancel.dlx
  ofb_consents_authorization:
    queue: ofb.consents.auth.queue
    exchange: ofb.consents.auth.ex
    dlq: ofb.consents.authn.dlq
    dlx: ofb.consents.auth.dlx
---
spring:
  config:
    activate:
      on-profile: k8s
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.152.183.103:3000/eureka
amqp:
  audit_services:
    queue: ofb.audit.queue
    exchange: ofb.audit.ex
    dlq: ofb.audit.dlq
    dlx: ofb.audit.dlx
  ofb_consents_cancel:
    queue: ofb.consents.cancel.queue
    exchange: ofb.consents.cancel.ex
    dlq: ofb.consents.cancel.dlq
    dlx: ofb.consents.cancel.dlx
  ofb_consents_authorization:
    queue: ofb.consents.auth.queue
    exchange: ofb.consents.auth.ex
    dlq: ofb.consents.authn.dlq
    dlx: ofb.consents.auth.dlx