apiVersion: v1
kind: Service
metadata:
  name: oauth2-users-business-svc
  labels:
    app: oauth2-users-business-svc
spec:
  type: ClusterIP
  selector:
    app: oauth2-users-business-pod
  ports:
    - port: 6005
      targetPort: 6005
