apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tican-audit-services-pvc
  labels:
    app: tican-audit-services-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

