apiVersion: v1
kind: Service
metadata:
  name: tican-audit-services-nodeport
  labels:
    app: tican-audit-services-nodeport
spec:
  type: NodePort
  clusterIP: 10.152.183.115
  ports:
    - port: 3041
      nodePort: 30041
  selector:
    app: tican-audit-services-pod

