package com.tican.lib.commons.jpa;

public enum RequestFilterPredicatesEnum {
   LIKE, EQUAL_STRING, EQUAL_NUMBER, EQUAL_DATE, 
   BETWEEN_NUMBERS, BETWEEN_DATES, 
   GREATER_NUMBER_THAN, GREATER_DATE_THAN,
   GREATER_NUMBER_THAN_OR_EQUAL, GREATER_DATE_THAN_OR_EQUAL,
   LESS_NUMBER_THAN, LESS_DATE_THAN, 
   LESS_NUMBER_THAN_OR_EQUAL, LESS_DATE_THAN_OR_EQUAL
}