apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-services-cmap
  labels:
    app: audit-services-cmap
data:
  API_LOGGING_LEVEL              : "error"
  API_SWAGGER_ENABLE             : "false"
  AUDIT_SERVICES_REPLICAS        : "3"
  
