# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: tican-eureka-pod
  labels:
    app: tican-eureka-pod
spec:
  containers:
    - name: tican-eureka-pod
      image: fras200627/tican-service-discovery:1.0.0
      ports:
        - containerPort: 5000
      env:
        - name: "spring.profiles.active"
          value: "dev"
        - name: "SERVICE_DISCOVERY_EXPOSE_PORT"
          value: "5000"
        - name: "PROFILE_ACTIVE"
          value: "dev"
        - name: "API_LOGGING_LEVEL"
          value: "trace"
          