spring:
  application:
    name: codetickets
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/ofb-batch?serverTimezone=UTC
      jdbcUrl: jdbc:mysql://localhost:3306/ofb-batch?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL_USER:root}
      password: ${MYSQL_ROOT_PWD:root}
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update