apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tican-api-gateway-pvc
  labels:
    app: tican-api-gateway-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
