apiVersion: v1
kind: ConfigMap
metadata:
  name: substances-domain-cmap
  labels:
    app: substances-domain-cmap
data:
  API_LOGGING_LEVEL              : "error"
  API_SWAGGER_ENABLE             : "false"
  SUBSTANCES_DOMAIN_REPLICAS : "1"
  
