apiVersion: v1
kind: Service
metadata:
  name: substances-domain-nodeport
  labels:
    app: substances-domain-nodeport
spec:
  type: NodePort
  ports:
    - port: 6007
      nodePort: 31007
  selector:
    app: substances-domain-pod
