apiVersion: v1
kind: Service
metadata:
  name: oauth2-clients-domain-nodeport
  labels:
    app: oauth2-clients-domain-nodeport
spec:
  type: NodePort
  ports:
    - port: 6003
      nodePort: 31003
  selector:
    app: oauth2-clients-domain-pod
