server:
  port: ${AUTHENTICATION_SERVER_INTERNAL_PORT:0}

#########################################################
app:
  environment: ${PROFILE_ACTIVE:k8s}
  app_info:
    name: ${API_NAMESPACE:Tican Services K8S}
    title: ${API_NAMESPACE_TITLE:Tican Services Kubernetes Engine} - Auth Server
    version: ${API_VERSION:1.0.0}
    build: ${API_BUILD:v.02_2025}

#########################################################
spring:
  application:
    name: auth-server-services
  session:
    store-type: jdbc
  security:
    filter:
      dispatcher-types: request
    auth:
      provider-uri: http://${AUTHENTICATION_SERVER_HOST_NAME:api-gateway-services}:${API_GATEWAY_EXPOSE_PORT:5001}/auth-server-svc
      jks:
        keypass: ${AUTH_JKS_KEYPASS:123456}
        storepass: ${AUTH_JKS_STOREPASS:123456}
        alias: ${AUTH_JKS_ALIAS:tican}
        path: ${AUTH_JKS_PATH:keystore/tican.jks}
  datasource:
    url: jdbc:mysql://${MYSQL_CLUSTERIP_SVC:db-mysql-svc}:${MYSQL_INTERNAL_PORT:3306}/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        format_sql: true    
    show-sql: ${API_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${API_HIBERNATE_DDL_AUTO:none}
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:mq-rabbit-svc}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:tican}
    password: ${RABBITMQ_DEFAULT_PWD:tican}

#########################################################
eureka:
  instance:
    hostname: auth-server-services
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_CLUSTERIP_SVC:discovery-services-svc}:${SERVICE_DISCOVERY_INTERNAL_PORT:6000}/eureka

#########################################################
resilience4j:
  circuitBreaker:
    instances:
      securityDomain:
        waitDurationInOpenState: 50s
        minimumNumberOfCalls: 2
        slidingWindowSize: 3

#########################################################        
amqp:
  audit_services:
    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}

#########################################################
logging:
  level:
    com:
      tican: ${API_LOGGING_LEVEL:error}
    org:
      springframework: ${API_LOGGING_LEVEL:error}

#########################################################
springdoc:
  api-docs:
    enabled: ${API_SWAGGER_ENABLE:true}
  packagesToScan: com.tican
  pathsToMatch: /**
  swagger-ui:
    enable: true
    operationsSorter: alpha
    path: /docs
    tagsSorter: alpha
    