apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tican-oauth2-users-business-pvc
  labels:
    app: tican-oauth2-users-business-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
