apiVersion: v1
kind: Service
metadata:
  name: tican-oauth2-users-business-svc
  labels:
    app: tican-oauth2-users-business-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.125
  selector:
    app: tican-oauth2-users-business-pod
  ports:
    - port: 3071
      targetPort: 30071
      
    
  