apiVersion: v1
kind: Service
metadata:
  name: audit-services-nodeport
  labels:
    app: audit-services-nodeport
spec:
  type: NodePort
  ports:
    - port: 6010
      nodePort: 31011
  selector:
    app: audit-services-pod
