apiVersion: v1
kind: Service
metadata:
  name: tican-audit-services-svc
  labels:
    app: tican-audit-services-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.113
  selector:
    app: tican-audit-services-pod
  ports:
    - port: 3041
      targetPort: 30041
      
    
  