apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-rabbit-services
  labels:
    app: mq-rabbit-services
    hostname: mq-rabbit-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-rabbit-pod
  template:
    metadata:
      name: mq-rabbit-pod
      labels:
        app: mq-rabbit-pod
    spec:
      containers:
        - name: mq-rabbit-container
          image: 'fras200627/mq-tican-rabbit:1.0.0'
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: config-map-defaults
            - configMapRef:
                name: mq-rabbit-cmap
          volumeMounts:
            - name: mq-rabbit-persist
              mountPath: /default/mq-rabbit-pvc
      volumes:
        - name: mq-rabbit-persist
          persistentVolumeClaim:
            claimName: mq-rabbit-pvc
  serviceName: mq-rabbit-services-stateful          