# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: tican-discovery-services-svc
  labels:
    app: tican-discovery-services-svc
spec:
  type: ClusterIP
  selector:
    app: tican-discovery-services-pod
  ports:
    - port: 30000
      targetPort: 3000
      
    
  