# ---------------------------------------------------------------
# This script includes volume
# ---------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: tican-discovery-services-pod
  labels:
    app: tican-discovery-services-pod
spec:
  containers:
    - name: tican-discovery-services-pod
      image: fras200627/tican-discovery-services:3.0.0
      volumeMounts:
        - mountPath: /discovery-services
          name: tican-discovery-services-vol
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: tican-discovery-services-cmap 
  volumes:
    - name: tican-discovery-services-vol
      hostPath:
        path: /C/temp/kubernetes/volumes
        type: Directory