<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.18</version>
		<relativePath/>
	</parent>

	<groupId>com.ofb</groupId>
	<artifactId>sboot-camel-orch-ofb-resources</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>
	<name>sboot-camel-orch-ofb-resources</name>
	<description>Project OFB - Orch Resources</description>

	<properties>
		<!-- Project default infos -->
		<java.version>17</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEnconding>UTF-8</project.build.sourceEnconding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<!-- ATTENTION! IMPORTANT! Generate.OpenAPI Parameters Configuration-->
		<exclude.generate.sources.tests>${project.build.directory}/generated-sources/ofb/resources/src/test/java/org</exclude.generate.sources.tests>
		<exclude.generate.sources.org>${project.build.directory}/generated-sources/ofb/resources/src/main/java/org</exclude.generate.sources.org>
		<openapi.input.sec.path>${project.basedir}/src/main/resources/openapi</openapi.input.sec.path>
		<openapi.api.package.structure>com.ofb.resources.server.handler</openapi.api.package.structure>
		<openapi.model.package.structure>com.ofb.resources.server.model</openapi.model.package.structure>
		<openapi.output.path>target/generated-sources/ofb/resources</openapi.output.path>

		<!-- Project OFB Lib dependencies-->
		<ofb-lib-common-tools-version>1.0.0</ofb-lib-common-tools-version>
		<ofb-lib-autoconfigure-amqp-version>1.0.0</ofb-lib-autoconfigure-amqp-version>
		<ofb-lib-autoconfigure-handlers-version>1.0.0</ofb-lib-autoconfigure-handlers-version>
		<ofb-lib-autoconfigure-interceptors-version>1.0.0</ofb-lib-autoconfigure-interceptors-version>
		<ofb-lib-autoconfigure-security-version>1.0.0</ofb-lib-autoconfigure-security-version>

		<!-- additional information used in <goal>build-info</goal> -->
		<info.additional.project.module.name>ORCH.RESOURCES</info.additional.project.module.name>
		<info.additional.contact.name>fras200627</info.additional.contact.name>
		<info.additional.contact.url>*</info.additional.contact.url>
		<info.additional.contact.email>fras200627@gmail.com</info.additional.contact.email>
		<info.additional.license.name>fras200627</info.additional.license.name>
		<info.additional.license.url>*</info.additional.license.url>

		<!-- Project Core Dependencies -->
		<org.springframework.cloud.version>2021.0.8</org.springframework.cloud.version>

		<spring-security-oauth2-authorization-server-version>0.2.3</spring-security-oauth2-authorization-server-version>
		<resilience4j-spring-boot2-version>1.7.0</resilience4j-spring-boot2-version>
		<org.mapstruct.version>1.6.3</org.mapstruct.version>
		<mysql-connector-java-version>8.0.33</mysql-connector-java-version>
		<lombok.version>1.18.36</lombok.version>
		<apache-camel-version>3.22.4</apache-camel-version>

		<!-- Settings dependencies for the OpenAPI generator and Swagger-UI-->
		<openapi-springdoc-version>1.8.0</openapi-springdoc-version>
		<openapi-code-generator-version>7.12.0</openapi-code-generator-version>

		<!-- Required dependencies for the OpenAPI generator -->
		<io.swagger.core.v3.version>2.2.21</io.swagger.core.v3.version>
		<nimbus-jose-jwt.version>9.22</nimbus-jose-jwt.version>
		<gson-version>2.10.1</gson-version>
		<gson-fire-version>1.9.0</gson-fire-version>
		<okhttp-version>4.12.0</okhttp-version>
		<jackson-databind-nullable-version>0.2.6</jackson-databind-nullable-version>
		<junit-jupiter-engine-version>5.8.2</junit-jupiter-engine-version>
		<javax.annotation.version>1.3.2</javax.annotation.version>
		<javax-validation-api-version>2.0.1.Final</javax-validation-api-version>
		<org.apache.oltu.oauth2.client.version>1.0.2</org.apache.oltu.oauth2.client.version>
		<com.google.code.findbugs.version>3.0.2</com.google.code.findbugs.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${org.springframework.cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- Lib dependencies-->
		<dependency>
			<groupId>com.ofb</groupId>
			<artifactId>sboot-lib-ofb-common-tools</artifactId>
			<version>${ofb-lib-common-tools-version}</version>
		</dependency>
		<dependency>
			<groupId>com.ofb</groupId>
			<artifactId>sboot-lib-ofb-autoconfigure-amqp</artifactId>
			<version>${ofb-lib-autoconfigure-amqp-version}</version>
		</dependency>
		<dependency>
			<groupId>com.ofb</groupId>
			<artifactId>sboot-lib-ofb-autoconfigure-handlers</artifactId>
			<version>${ofb-lib-autoconfigure-handlers-version}</version>
		</dependency>
		<dependency>
			<groupId>com.ofb</groupId>
			<artifactId>sboot-lib-ofb-autoconfigure-interceptors</artifactId>
			<version>${ofb-lib-autoconfigure-interceptors-version}</version>
		</dependency>
		<dependency>
			<groupId>com.ofb</groupId>
			<artifactId>sboot-lib-ofb-autoconfigure-security</artifactId>
			<version>${ofb-lib-autoconfigure-security-version}</version>
		</dependency>

		<!-- Spring core dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Spring Cloud -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>

		<!-- ApacheCamel -->
		<dependency>
			<groupId>org.apache.camel.springboot</groupId>
			<artifactId>camel-spring-boot-starter</artifactId>
			<version>${apache-camel-version}</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-core-engine</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-main</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-log</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-file</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-rest</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-jetty</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-xpath</artifactId>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-http</artifactId>-->
<!--			<version>3.22.4</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.camel</groupId>-->
<!--			<artifactId>camel-direct</artifactId>-->
<!--		</dependency>-->

		<!-- Spring Test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>

		<!-- Spring Cloud Backend Circuit-Breaker Services -->
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>${resilience4j-spring-boot2-version}</version>
		</dependency>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- MapStruct -->
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>

		<!-- SWAGGER-UI:: SpringDoc and Swagger UI resources -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>${openapi-springdoc-version}</version>
		</dependency>

		<!-- OpenAPI CORE:: Required dependencies for the OpenAPI generator -->
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>${javax.annotation.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>${javax-validation-api-version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>${com.google.code.findbugs.version}</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>${okhttp-version}</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>logging-interceptor</artifactId>
			<version>${okhttp-version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson-version}</version>
		</dependency>
		<dependency>
			<groupId>io.gsonfire</groupId>
			<artifactId>gson-fire</artifactId>
			<version>${gson-fire-version}</version>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${jackson-databind-nullable-version}</version>
		</dependency>

		<!-- OpenAPI TESTS:: Required dependencies for the OpenAPI generator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.camel</groupId>
			<artifactId>camel-test-spring-junit5</artifactId>
			<version>${apache-camel-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit-jupiter-engine-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Runs the Lombok and MapStruct Processors required for lombok.* annotations and created 'MapStruct' mappers. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>1.6.3</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.36</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>

			<!-- removes unwanted test class instances and classes from /main/src/java/?/org/openapi generated by Generate.OpenAPI. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<delete dir="${exclude.generate.sources.tests}" />
								<delete dir="${exclude.generate.sources.org}" />
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Runs Generate.OpenAPI from the *.yaml files included in the project. -->
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-code-generator-version}</version>
				<executions>
					<execution>
						<id>generator-health-checks</id> <!-- It is not optional and must have a unique id -->
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
							 generatorName Types:
							 OpenAPI Documentation for API Servers and API Clients in
							 https://openapi-generator.tech/docs/generators/
							 The 'spring' type generates a server package ++++++++++++++-->
							<generatorName>spring</generatorName>
							<!-- OpenAPI generated artifacts settings ++++++++++++++++++-->
							<inputSpec>${openapi.input.sec.path}/server/openapi-health-checks.yaml</inputSpec>
							<apiPackage>com.ofb.resources.server.health.checks.handler</apiPackage>
							<modelPackage>com.ofb.resources.server.health.checks.model</modelPackage>
							<output>target/generated-sources/ofb/resources</output>
							<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
							<skipValidateSpec>true</skipValidateSpec>
							<configOptions>
								<invokerpackage>com.ofb.resources.server.health.checks.handler</invokerpackage>
								<delegatePattern>true</delegatePattern>
								<requestMappingMode>controller</requestMappingMode> <!-- Default -->
								<dateLibrary>java8</dateLibrary>
								<useBeanValidation>true</useBeanValidation>
								<performBeanValidation>true</performBeanValidation>
								<openApiNullable>true</openApiNullable>
								<documentationProvider>springdoc</documentationProvider>
								<library>spring-boot</library>
								<useSpringBoot3>false</useSpringBoot3>
								<generateBuilders>true</generateBuilders>
								<generateConstructorWithAllArgs>true</generateConstructorWithAllArgs>
								<generatedConstructorWithRequiredArgs>true</generatedConstructorWithRequiredArgs>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>generator-resources-server</id> <!-- It is not optional and must have a unique id -->
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
							 generatorName Types:
							 OpenAPI Documentation for API Servers and API Clients in
							 https://openapi-generator.tech/docs/generators/
							 The 'spring' type generates a server package ++++++++++++++-->
							<generatorName>spring</generatorName>
							<!-- OpenAPI generated artifacts settings ++++++++++++++++++-->
							<inputSpec>${openapi.input.sec.path}/server/openapi-resources.3.0.0.yaml</inputSpec>
							<apiPackage>com.ofb.resources.server.api.handler</apiPackage>
							<modelPackage>com.ofb.resources.server.api.model</modelPackage>
							<output>target/generated-sources/ofb/resources</output>
							<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
							<skipValidateSpec>true</skipValidateSpec>
							<configOptions>
								<invokerpackage>com.ofb.resources.server.api.handler</invokerpackage>
								<delegatePattern>true</delegatePattern>
								<requestMappingMode>controller</requestMappingMode> <!-- Default -->
								<dateLibrary>java8</dateLibrary>
								<useBeanValidation>true</useBeanValidation>
								<performBeanValidation>true</performBeanValidation>
								<openApiNullable>true</openApiNullable>
								<documentationProvider>springdoc</documentationProvider>\
								<library>spring-boot</library>
								<useSpringBoot3>false</useSpringBoot3>
								<generateBuilders>true</generateBuilders>
								<generateConstructorWithAllArgs>true</generateConstructorWithAllArgs>
								<generatedConstructorWithRequiredArgs>true</generatedConstructorWithRequiredArgs>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>generator-atom-authorization-client</id> <!-- It is not optional and must have a unique id -->
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
							 generatorName Types:
							 OpenAPI Documentation for API Servers and API Clients in
							 https://openapi-generator.tech/docs/generators/
							 The 'spring' type generates a server package ++++++++++++++-->
							<generatorName>java</generatorName>
							<!-- OpenAPI generated artifacts settings ++++++++++++++++++-->
							<inputSpec>${openapi.input.sec.path}/client/openapi-atom-authorization-server.1.0.0.yaml</inputSpec>
							<apiPackage>com.ofb.resources.client.authorization.handler</apiPackage>
							<modelPackage>com.ofb.resources.client.authorization.model</modelPackage>
							<output>${openapi.output.path}</output>
							<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
							<configOptions>
								<invokerpackage>com.ofb.resources.client.authorization.handler</invokerpackage>
								<library>resttemplate</library>
								<documentationProvider>source</documentationProvider>
								<generateBuilders>true</generateBuilders>
								<generateClientAsBean>true</generateClientAsBean>
								<generateConstructorWithAllArgs>true</generateConstructorWithAllArgs>
								<sourcefolder>src/gen/java/main</sourcefolder>
								<java8>true</java8>
								<datelibrary>java8</datelibrary>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>generator-atom-resources-client</id> <!-- It is not optional and must have a unique id -->
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
							 generatorName Types:
							 OpenAPI Documentation for API Servers and API Clients in
							 https://openapi-generator.tech/docs/generators/
							 The 'spring' type generates a server package ++++++++++++++-->
							<generatorName>java</generatorName>
							<!-- OpenAPI generated artifacts settings ++++++++++++++++++-->
							<inputSpec>${openapi.input.sec.path}/client/openapi-atom-resources-server.1.0.0.yaml</inputSpec>
							<apiPackage>com.ofb.resources.client.resources.handler</apiPackage>
							<modelPackage>com.ofb.resources.client.resources.model</modelPackage>
							<output>${openapi.output.path}</output>
							<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
							<configOptions>
								<invokerpackage>com.ofb.resources.client.resources.handler</invokerpackage>
								<library>resttemplate</library>
								<documentationProvider>source</documentationProvider>
								<generateBuilders>true</generateBuilders>
								<generateClientAsBean>true</generateClientAsBean>
								<generateConstructorWithAllArgs>true</generateConstructorWithAllArgs>
								<sourcefolder>src/gen/java/main</sourcefolder>
								<java8>true</java8>
								<datelibrary>java8</datelibrary>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>build-info</id>
						<goals>
							<goal>build-info</goal>
						</goals>
						<configuration>
							<additionalProperties>
								<project.module.name>${info.additional.project.module.name}</project.module.name>
								<project.title>${project.name}</project.title>
								<project.description>${project.description}</project.description>
								<project.version>${java.version}</project.version>
								<contact.name>${info.additional.contact.name}</contact.name>
								<contact.url>${info.additional.contact.url}</contact.url>
								<contact.email>${info.additional.contact.email}</contact.email>
								<license.name>${info.additional.license.name}</license.name>
								<license.url>${info.additional.license.url}</license.url>
							</additionalProperties>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>