apiVersion: v1
kind: ConfigMap
metadata:
  name: substances-business-cmap
  labels:
    app: substances-business-cmap
data:
  API_LOGGING_LEVEL              : "error"
  API_SWAGGER_ENABLE             : "false"
  SUBSTANCES_BUSINESS_REPLICAS     : "1"
  
