apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: substances-business-pvc
  labels:
    app: substances-business-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
