apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: substances-business-services
  labels:
    app: substances-business-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: substances-business-pod
  template:
    metadata:
      name: substances-business-pod
      labels:
        app: substances-business-pod
    spec:
      containers:
        - name: substances-business-container
          image: fras200627/substances-business:1.0.0
          ports:
            - containerPort: 6008
          envFrom:
            - configMapRef:
                name: config-map-defaults
            - configMapRef:
                name: substances-business-cmap  
          volumeMounts:
            - name: substances-business-persist
              mountPath: /default/substances-business-pvc
      volumes:
        - name: substances-business-persist
          persistentVolumeClaim:
            claimName: substances-business-pvc
  serviceName: substances-business-services-stateful
    