apiVersion: v1
kind: Service
metadata:
  name: substances-business-svc
  labels:
    app: substances-business-svc
spec:
  type: ClusterIP
  selector:
    app: substances-business-pod
  ports:
    - port: 6008
      targetPort: 6008
