apiVersion: v1
kind: Service
metadata:
  name: substances-business-nodeport
  labels:
    app: substances-business-nodeport
spec:
  type: NodePort
  ports:
    - port: 6008
      nodePort: 31008
  selector:
    app: substances-business-pod
