<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.11</version>
		<relativePath/>
	</parent>
	
	<groupId>com.ofb</groupId>
	<artifactId>ofb-authentication-server</artifactId>
	<packaging>jar</packaging>
	<version>1.0.0</version>
	<name>ofb-authentication-server</name>
	<description>Project OFB Authentication Server</description>

	<properties>
		<!-- default builder infos -->
		<java.version>17</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEnconding>UTF-8</project.build.sourceEnconding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<!-- Necessary to avoid conflicts with OpenAPI -->
<!--		<start-class>com.ofb.authentication.StartApplication</start-class>-->

		<!-- additional information used in <goal>build-info</goal> -->
		<info.additional.project.module.name>AUTH.SERVER</info.additional.project.module.name>
		<info.additional.contact.name>fras200627</info.additional.contact.name>
		<info.additional.contact.url>*</info.additional.contact.url>
		<info.additional.contact.email>fras200627@gmail.com</info.additional.contact.email>
		<info.additional.license.name>fras200627</info.additional.license.name>
		<info.additional.license.url>*</info.additional.license.url>

		<exclude.generate.sources.tests>${project.build.directory}/generated-sources/server/src/test/java/org</exclude.generate.sources.tests>
		<exclude.generate.sources.org>${project.build.directory}/generated-sources/server/src/main/java/org</exclude.generate.sources.org>

		<!-- Project Core Dependencies -->
		<org.springframework.cloud.version>2021.0.8</org.springframework.cloud.version>
		<resilience4j-spring-boot2-version>1.7.0</resilience4j-spring-boot2-version>
		<org.mapstruct.version>1.6.3</org.mapstruct.version>
		<mysql-connector-java-version>8.0.33</mysql-connector-java-version>
		<lombok.version>1.18.36</lombok.version>

		<!-- Settings dependencies for the OpenAPI generator and Swagger-UI-->
		<openapi-springdoc-version>1.8.0</openapi-springdoc-version>
		<openapi-code-generator-version>7.12.0</openapi-code-generator-version>

		<!-- Required dependencies for the OpenAPI generator -->
		<gson-version>2.10.1</gson-version>
		<gson-fire-version>1.9.0</gson-fire-version>
		<okhttp-version>4.12.0</okhttp-version>
		<jackson-databind-nullable-version>0.2.6</jackson-databind-nullable-version>
		<junit-jupiter-engine-version>5.8.2</junit-jupiter-engine-version>
		<javax.annotation.version>1.3.2</javax.annotation.version>
		<javax-validation-api-version>2.0.1.Final</javax-validation-api-version>
		<org.apache.oltu.oauth2.client.version>1.0.2</org.apache.oltu.oauth2.client.version>
		<com.google.code.findbugs.version>3.0.2</com.google.code.findbugs.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>2021.0.8</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- App core dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-authorization-server</artifactId>
			<version>0.2.3</version>
		</dependency>

		<!-- Spring Security -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session-jdbc</artifactId>
		</dependency>

		<!-- Spring Cloud Backend Circuit-Breaker Services -->
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>${resilience4j-spring-boot2-version}</version>
		</dependency>

		<!-- Spring Data -->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${mysql-connector-java-version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- MapStruct -->
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>

		<!-- SWAGGER-UI:: SpringDoc and Swagger UI resources -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>${openapi-springdoc-version}</version>
		</dependency>

		<!-- OpenAPI CORE:: Required dependencies for the OpenAPI generator -->
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>${javax.annotation.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>${javax-validation-api-version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>${com.google.code.findbugs.version}</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>${okhttp-version}</version>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>logging-interceptor</artifactId>
			<version>${okhttp-version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson-version}</version>
		</dependency>
		<dependency>
			<groupId>io.gsonfire</groupId>
			<artifactId>gson-fire</artifactId>
			<version>${gson-fire-version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.oltu.oauth2</groupId>
			<artifactId>org.apache.oltu.oauth2.client</artifactId>
			<version>${org.apache.oltu.oauth2.client.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${jackson-databind-nullable-version}</version>
		</dependency>

		<!-- OpenAPI TESTS:: Required dependencies for the OpenAPI generator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit-jupiter-engine-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.2.21</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>nimbus-jose-jwt</artifactId>
			<version>9.22</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>nimbus-jose-jwt</artifactId>
			<version>9.22</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Runs the Lombok and MapStruct Processors required for lombok.* annotations and created 'MapStruct' mappers. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>1.6.3</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.36</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>

			<!-- removes unwanted test class instances and classes from /main/src/java/?/org/openapi generated by Generate.OpenAPI. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<delete dir="${exclude.generate.sources.tests}" />
								<delete dir="${exclude.generate.sources.org}" />
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Runs Generate.OpenAPI from the *.yaml files included in the project. -->
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-code-generator-version}</version>
				<executions>
					<execution>
						<id>generator-api-health-checks</id> <!-- It is not optional and must have a unique id -->
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
							 generatorName Types:
							 OpenAPI Documentation for API Servers and API Clients in
							 https://openapi-generator.tech/docs/generators/
							 The 'spring' type generates a server package ++++++++++++++-->
							<generatorName>spring</generatorName>
							<!-- OpenAPI generated artifacts settings ++++++++++++++++++-->
							<inputSpec>${project.basedir}/src/main/resources/openapi/server/api-health-checks.yaml</inputSpec>
							<apiPackage>com.ofb.authentication.server.handler</apiPackage>
							<modelPackage>com.ofb.authentication.server.model</modelPackage>
							<output>target/generated-sources/server</output>
							<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
							<skipValidateSpec>true</skipValidateSpec>
							<configOptions>
								<delegatePattern>true</delegatePattern>
								<requestMappingMode>controller</requestMappingMode> <!-- Default -->
								<dateLibrary>java8</dateLibrary>
								<useBeanValidation>true</useBeanValidation>
								<performBeanValidation>true</performBeanValidation>
								<openApiNullable>true</openApiNullable>
								<documentationProvider>springdoc</documentationProvider>
								<library>spring-boot</library>
								<useSpringBoot3>false</useSpringBoot3>
								<generateBuilders>true</generateBuilders>
								<generateConstructorWithAllArgs>true</generateConstructorWithAllArgs>
								<generatedConstructorWithRequiredArgs>true</generatedConstructorWithRequiredArgs>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>build-info</id>
						<goals>
							<goal>build-info</goal>
						</goals>
						<configuration>
							<additionalProperties>
								<project.module.name>${info.additional.project.module.name}</project.module.name>
								<project.title>${project.name}</project.title>
								<project.description>${project.description}</project.description>
								<project.version>${java.version}</project.version>
								<contact.name>${info.additional.contact.name}</contact.name>
								<contact.url>${info.additional.contact.url}</contact.url>
								<contact.email>${info.additional.contact.email}</contact.email>
								<license.name>${info.additional.license.name}</license.name>
								<license.url>${info.additional.license.url}</license.url>
							</additionalProperties>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
