spring:
  application:
    name: ofb-lib-autoconfigure-amqp
---
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: ${RABBITMQ_HOST_NAME:localhost}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PWD:guest}

# rabbitmq-plugins enable rabbitmq_management
# http://localhost:15672 (guest/guest)
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:ofb}
    password: ${RABBITMQ_DEFAULT_PASS:ofb}

---
spring:
  config:
    activate:
      on-profile: k8s
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:ofb}
    password: ${RABBITMQ_DEFAULT_PASS:ofb}
