spring:
  application:
    name: ofb-lib-autoconfigure-amqp
---
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: ${RABBITMQ_HOST_NAME:localhost}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PWD:guest}
#amqp:
#  audit_services:
#    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
#    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
#    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
#    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:tican}
    password: ${RABBITMQ_DEFAULT_PASS:tican}
#amqp:
#  audit_services:
#    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
#    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
#    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
#    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}
---
spring:
  config:
    activate:
      on-profile: k8s
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:tican}
    password: ${RABBITMQ_DEFAULT_PASS:tican}
#amqp:
#  audit_services:
#    audit_queue: ${API_AMQP_AUDIT_QUEUE:tican.audit.queue}
#    audit_exchange: ${API_AMQP_AUDIT_EX:tican.audit.ex}
#    audit_dlq: ${API_AMQP_AUDIT_DLQ:tican.audit.dlq}
#    audit_dlx: ${API_AMQP_AUDIT_DLX:tican.audit.dlx}