spring:
  application:
    name: ofb-lib-autoconfigure-amqp
---
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: ${RABBITMQ_HOST_NAME:localhost}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PWD:guest}

amqp:
  ofb:
    exchange-direct: "ofb.exchange.direct"
    audit:
      http-requests:
        queue: "ofb.audit.http.requests"
        routing-key: "audit.http.requests"
      consents-authorization:
        queue: "ofb.audit.consents.authorization"
        routing-key: "audit.consents.auth"
      consents-cancellation:
        queue: "ofb.audit.consents.cancellation"
        routing-key: "audit.consents.cancel"
      consents-revoke:
        queue: "ofb.audit.consents.revoke"
        routing-key: "audit.consents.revoke"
    consents:
      authorization:
        queue: "ofb.consents.authorization"
        routing-key: "exec.consents.auth"
      cancellation:
        queue: "ofb.consents.cancellation"
        routing-key: "exec.consents.cancel"


# rabbitmq-plugins enable rabbitmq_management
# http://localhost:15672 (guest/guest)
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:ofb}
    password: ${RABBITMQ_DEFAULT_PASS:ofb}

---
spring:
  config:
    activate:
      on-profile: k8s
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:ofb}
    password: ${RABBITMQ_DEFAULT_PASS:ofb}
