apiVersion: v1
kind: ConfigMap
metadata:
  name: products-domain-cmap
  labels:
    app: products-domain-cmap
data:
  API_LOGGING_LEVEL              : "error"
  API_SWAGGER_ENABLE             : "false"
  PRODUCTS_DOMAIN_REPLICAS : "1"
  
