apiVersion: v1
kind: Service
metadata:
  name: products-domain-svc
  labels:
    app: products-domain-svc
spec:
  type: ClusterIP
  selector:
    app: products-domain-pod
  ports:
    - port: 6009
      targetPort: 6009
