/***********************************************************************/
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
/

/* Create Audit sequence */
CREATE SEQUENCE TICAN2.SEQ_AUDIT
MINVALUE 0
MAXVALUE 9999999999
START WITH 1000
INCREMENT BY 1
CACHE 20;
/

GRANT ALL ON TICAN2.SEQ_AUDIT TO TICAN2;
GRANT ALL ON TICAN2.SEQ_AUDIT TO TICAN2_OWNER;
GRANT SELECT ON TICAN2.SEQ_AUDIT TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.AUDIT_SEQUENCE FOR TICAN2.SEQ_AUDIT;
/

/* Create Substance sequence */
CREATE SEQUENCE TICAN2.SEQ_SUBSTANCES
MINVALUE 0
MAXVALUE 99999999
START WITH 100000
INCREMENT BY 1
CACHE 20;
/

GRANT ALL ON TICAN2.SEQ_SUBSTANCES TO TICAN2;
GRANT ALL ON TICAN2.SEQ_SUBSTANCES TO TICAN2_OWNER;
GRANT SELECT ON TICAN2.SEQ_SUBSTANCES TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.SUBSTANCES_SEQUENCE FOR TICAN2.SEQ_SUSBTANCES;
/

/* Create Products Sequence */
CREATE SEQUENCE TICAN2.SEQ_PRODUCTS
MINVALUE 0
MAXVALUE 99999999
START WITH 100000
INCREMENT BY 1
CACHE 20;
/

GRANT ALL PRIVILEGES ON TICAN2.SEQ_PRODUCTS TO TICAN2; 
GRANT ALL PRIVILEGES ON TICAN2.SEQ_PRODUCTS TO TICAN2_OWNER; 
GRANT SELECT ON TICAN2.SEQ_PRODUCTS TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.PRODUCTS_SEQUENCE FOR TICAN2.SEQ_PRODUCTS;
/

/* Create Users Sequence */
CREATE SEQUENCE TICAN2.SEQ_USERS
MINVALUE 0
MAXVALUE 99999999
START WITH 4
INCREMENT BY 1
CACHE 20;
/

GRANT ALL PRIVILEGES ON TICAN2.SEQ_USERS TO TICAN2;
GRANT ALL PRIVILEGES ON TICAN2.SEQ_USERS TO TICAN2_OWNER;
GRANT SELECT ON TICAN2.SEQ_USERS TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.USERS_SEQUENCE FOR TICAN2.SEQ_USERS;
/


