/***********************************************************************/
/* Create table Products */
CREATE TABLE TICAN2.TB_AUDIT
(
  TICKET                        NUMBER          NOT NULL,
  REQUEST_TIME                  VARCHAR2(200),
  REQUEST_URI                   VARCHAR2(400),
  REQUEST_METHOD                VARCHAR2(100),
  REQUEST_USER_NAME             VARCHAR2(100),
  PAYLOAD                       VARCHAR2(4000),
  PRIMARY KEY (TICKET)
) tablespace USERS
  pctfree 10 pctused 40
  initrans 1 maxtrans 255
  STORAGE (initial 64K next 1M minextents 1
          maxextents UNLIMITED
);
/
GRANT ALL ON TICAN2.TB_AUDIT TO TICAN2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN2.TB_AUDIT TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.TABLE_AUDIT FOR TICAN2.TB_AUDIT;
/
CREATE TABLE TICAN2.TB_AUDIT_2
(
  ID                            NUMBER(10)      NOT NULL,
  TICKET                        VARCHAR2(9)     NOT NULL,
  INTERACTION_ID                CHAR(36)        NOT NULL,
  REQUEST_TIME                  VARCHAR2(200)   NOT NULL,
  REQUEST_SOURCE                VARCHAR2(100)   NOT NULL,
  REQUEST_URI                   VARCHAR2(400)   NOT NULL,
  REQUEST_METHOD                VARCHAR2(100)   NOT NULL,
  REQUEST_USER_NAME             VARCHAR2(100)   NOT NULL,
  PAYLOAD                       VARCHAR2(4000)  NOT NULL,
  PRIMARY       KEY(ID)
) tablespace USERS
  pctfree 10 pctused 40
  initrans 1 maxtrans 255
  STORAGE (initial 64K next 1M minextents 1
          maxextents UNLIMITED
);
/
GRANT ALL ON TICAN2.TB_AUDIT_2 TO TICAN2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN2.TB_AUDIT_2 TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.TABLE_AUDIT FOR TICAN2.TB_AUDIT_2;
/

-- Create table Substances
CREATE TABLE TICAN2.TB_SUBSTANCES
(
  ID            NUMBER(10)       NOT NULL,
  SUBSTANCE     VARCHAR2(400)    NOT NULL,
  STATUS        VARCHAR2(30)     NOT NULL,
  PRIMARY       KEY(ID),
  UNIQUE        (SUBSTANCE)
) tablespace USERS
  pctfree 10 pctused 40 
  initrans 1 maxtrans 255
  STORAGE (initial 64K next 1M minextents 1
          maxextents UNLIMITED
);
/
GRANT ALL ON TICAN2.SEQ_SUBSTANCES TO TICAN2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN2.TB_SUBSTANCES TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.TABLE_SUSBTANCES FOR TICAN2.TB_SUBSTANCES;
/

/* Create table Products */
CREATE TABLE TICAN2.TB_PRODUCTS
(
  ID              NUMBER(10)    NOT NULL,
  STATUS          VARCHAR2(30)  NOT NULL,
  COD_GGREM       CHAR(15) NOT  NULL,
  PRODUCT         VARCHAR2(100) NOT NULL,
  ID_SUBSTANCE    NUMBER(10)    NOT NULL,
  PRESENTATION    VARCHAR2(200) NOT NULL,
  TERAPY_CLASS    VARCHAR2(200) NOT NULL,
  RESTRICTION     VARCHAR2(30)  NOT NULL,
  TAG             VARCHAR2(50)  NOT NULL,
  LABORATORY_NAME VARCHAR2(200) NOT NULL,
  CNPJ            VARCHAR2(18)  NOT NULL,
  REGISTRY_CODE   CHAR(13)      NOT NULL,
  EAN1_CODE       CHAR(14)      NOT NULL,
  EAN2_CODE       CHAR(14),
  EAN3_CODE       CHAR(14),
  PRODUCT_TYPE    VARCHAR2(20) NOT NULL,
  PRICE_RULE      VARCHAR2(20) NOT NULL,
  BASE_PRICE      NUMBER(18,4) NOT NULL,
  PRICE_ICMS_12   NUMBER(18,4) NOT NULL,
  PRICE_ICMS_17   NUMBER(18,4),
  PRICE_ICMS_18   NUMBER(18,4) NOT NULL,
  CREATE_AT       DATE DEFAULT SYSDATE NOT NULL ,
  MODIFY_AT       DATE DEFAULT SYSDATE NOT NULL ,
  USER_CODE       VARCHAR2(30) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (COD_GGREM, PRODUCT)
) tablespace USERS
  pctfree 10 pctused 40 
  initrans 1 maxtrans 255
  STORAGE (initial 64K next 1M minextents 1
          maxextents UNLIMITED
);
/
GRANT ALL ON TICAN2.TB_PRODUCTS TO TICAN2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN2.TB_PRODUCTS TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.TABLE_PRODUCTS FOR TICAN2.TB_PRODUCTS;
/

/* Create and populate Table Users */
CREATE TABLE TICAN2.TB_USERS(
    ID         NUMBER NOT NULL,
    LOGIN      VARCHAR2(100) NOT NULL,
    PASSWORD   VARCHAR2(255) NOT NULL,
    PROFILE    VARCHAR2(20) NOT NULL,
    EMAIL      VARCHAR2(500) NOT NULL,
    DEPARTMENT VARCHAR2(20) NOT NULL,
    STATUS     VARCHAR2(20) NOT NULL,
    CREATE_AT  TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFY_AT  TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_CODE  VARCHAR2(20) NOT NULL,
    PRIMARY     KEY(ID),
    UNIQUE      (LOGIN),
    UNIQUE      (EMAIL)
) tablespace USERS
  pctfree 10 pctused 40 
  initrans 1 maxtrans 255
  STORAGE (initial 64K next 1M minextents 1
          maxextents UNLIMITED
);
/
comment on table TICAN2.TB_USERS
  is 'Table System TICAN2 to Users';
comment on column TICAN2.TB_USERS.id
  is 'User id number';
comment on column TICAN2.TB_USERS.login
  is 'User Login name';
comment on column TICAN2.TB_USERS.password
  is 'User Password';
comment on column TICAN2.TB_USERS.profile
  is 'User Profile Code';
comment on column TICAN2.TB_USERS.email
  is 'User Email';
comment on column TICAN2.TB_USERS.department
  is 'User Department Name';
comment on column TICAN2.TB_USERS.status
  is 'User Status Code';
comment on column TICAN2.TB_USERS.create_at
  is 'User creation date';
comment on column TICAN2.TB_USERS.modify_at
  is 'Date of last modification of user data';
comment on column TICAN2.TB_USERS.user_code
  is 'User responsible for creating/modifying the user';
/
alter table TICAN2.TB_USERS
  add constraint USER_DEPARTMENT_CHECK
  check (UPPER(TRIM(DEPARTMENT)) IN ('SALES', 'PRODUCTS', 'PROJECTS', 'MARKETING'));
alter table TICAN2.TB_USERS
  add constraint USER_LOGIN_CHECK
  check (LENGTH(TRIM(LOGIN)) BETWEEN 5 AND 20);
alter table TICAN2.TB_USERS
  add constraint USER_PASSWORD_CHECK
  check (LENGTH(TRIM(PASSWORD)) BETWEEN 5 AND 200);
alter table TICAN2.TB_USERS
  add constraint USER_PROFILE_CHECK
  check (UPPER(TRIM(PROFILE)) IN ('ADMIN', 'USER', 'OPERATOR', 'ASSISTENT'));
alter table TICAN2.TB_USERS
  add constraint USER_STATUS_CHECK1
  check (UPPER(TRIM(STATUS)) IN ('ACTIVE', 'LOCKED', 'BLOCKED', 'INACTIVE', 'DISABLED'));
/
GRANT ALL ON TICAN2.TB_USERS TO TICAN2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN2.TB_USERS TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.TABLE_USERS FOR TICAN2.TB_USERS;
/

INSERT INTO TICAN2.TB_USERS (ID, LOGIN, PASSWORD, PROFILE, EMAIL, DEPARTMENT, STATUS, USER_CODE)
values (1, 'ADMIN', 'E778556C004B32A7', 'ADMIN', 'admin@tican.com', 'PROJECTS', 'ACTIVE', 'ADMIN');
/
COMMIT;
/
