/***********************************************************************/
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
/

-- Create View Products x Substances
CREATE OR REPLACE
VIEW TICAN2.VW_PRODUCTS_X_SUBSTANCES AS
SELECT 
A.ID,
A.STATUS         ,
A.COD_GGREM      ,
A.PRODUCT        ,
A.ID_SUBSTANCE   ,
B.SUBSTANCE    ,
B.STATUS       AS SUBSTANCE_STATUS,
A.PRESENTATION   ,
A.TERAPY_CLASS   ,
A.RESTRICTION    ,
A.TAG            ,
A.LABORATORY_NAME,
A.CNPJ           ,
A.REGISTRY_CODE  ,
A.EAN1_CODE      ,
A.EAN2_CODE      ,
A.EAN3_CODE      ,
A.PRODUCT_TYPE   ,
A.PRICE_RULE     ,
A.BASE_PRICE     ,
A.PRICE_ICMS_12  ,
A.PRICE_ICMS_17  ,
A.PRICE_ICMS_18  ,
A.CREATE_AT      ,
A.MODIFY_AT      ,
A.USER_CODE 
FROM 
TICAN2.TB_PRODUCTS A
INNER JOIN TICAN2.TB_SUBSTANCES B
ON A.ID_SUBSTANCE = B.ID
ORDER BY A.PRODUCT, A.LABORATORY_NAME;
/
GRANT ALL PRIVILEGES ON TICAN2.VW_PRODUCTS_X_SUBSTANCES TO TICAN2;
GRANT SELECT ON TICAN2.VW_PRODUCTS_X_SUBSTANCES TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.VIEW_PRODUCTS_X_SUBSTANCES FOR TICAN2.VW_PRODUCTS_X_SUBSTANCES;
/

CREATE MATERIALIZED VIEW "TICAN2"."VW_MATERIALIZED_PRODUCTS" 
( "ID", "STATUS", "COD_GGREM", "PRODUCT", 
  "ID_SUBSTANCE", "SUBSTANCE", 
  "SUBSTANCE_STATUS", "PRESENTATION", "TERAPY_CLASS", "RESTRICTION", 
  "TAG", "LABORATORY_NAME", "CNPJ", "REGISTRY_CODE", 
  "EAN1_CODE", "EAN2_CODE", "EAN3_CODE", "PRODUCT_TYPE", 
  "PRICE_RULE", "BASE_PRICE", "PRICE_ICMS_12", "PRICE_ICMS_17", 
  "PRICE_ICMS_18", "CREATE_AT", "MODIFY_AT", "USER_CODE")
  ORGANIZATION HEAP 
  PCTFREE 10 
  PCTUSED 40 
  INITRANS 1 
  MAXTRANS 255 
  NOCOMPRESS 
  LOGGING
  STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 
    FREELISTS 1 FREELIST 
    GROUPS 1 
    BUFFER_POOL DEFAULT 
    FLASH_CACHE DEFAULT 
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS 
  SELECT 
    P.*, 
    S.SUBSTANCE, 
    S.STATUS AS SUBSTANCE_STATUS
  FROM 
    TICAN2.TB_PRODUCTS P, TICAN2.TB_SUBSTANCES S
  WHERE 
    P.ID_SUBSTANCE = S.ID
  ORDER BY P.PRODUCT, S.SUBSTANCE;
/
GRANT ALL PRIVILEGES ON TICAN2.VW_MATERIALIZED_PRODUCTS TO TICAN2;
GRANT SELECT ON TICAN2.VW_MATERIALIZED_PRODUCTS TO TICAN2_USER;
CREATE OR REPLACE SYNONYM TICAN2.VIEW_PRODUCTS_X_SUBSTANCES FOR TICAN2.VW_MATERIALIZED_PRODUCTS;
/
