/***********************************************************************/
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
/

CREATE OR REPLACE NONEDITIONABLE TRIGGER TICAN2.TRG_BEFORE_INS_USERS
BEFORE INSERT ON TICAN2.TB_USERS
--BEFORE UPDATE ON TICAN2.TB_USERS
--BEFORE DELETE ON TICAN2.TB_USERS
--AFTER INSERT ON TICAN2.TB_USERS
--AFTER UPDATE ON TICAN2.TB_USERS
--AFTER DELTE ON TICAN2.TB_USERS
FOR EACH ROW
--[FOLLOWS | PRECEDES another_trigger]
--[ENABLE / DISABLE ]
--[WHEN condition]
DECLARE
v_ID            NUMBER:= 0;
v_COUNT         NUMBER:=0;
BEGIN

    --Normalize fields contents
    :NEW.LOGIN      := UPPER(TRIM(:NEW.LOGIN));
    :NEW.PASSWORD   := TRIM(:NEW.PASSWORD);
    :NEW.PROFILE    := UPPER(TRIM(:NEW.PROFILE));
    :NEW.EMAIL      := LOWER(TRIM(:NEW.EMAIL));
    :NEW.DEPARTMENT := UPPER(TRIM(:NEW.DEPARTMENT));
    :NEW.STATUS     := UPPER(TRIM(:NEW.STATUS));
    :NEW.USER_CODE  := UPPER(TRIM(:NEW.USER_CODE));

    --Validate User Login
    IF (:NEW.LOGIN IS NULL OR NOT (LENGTH(:NEW.LOGIN) BETWEEN 5 AND 20)) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#LoginValueRaise;
    END IF;
    SELECT COUNT(*) INTO v_COUNT FROM TICAN2.TB_USERS u
    WHERE
    u.LOGIN = :NEW.LOGIN;
    IF (v_COUNT != 0) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#LoginDuplicateRaise;
    END IF;

    --Validate Password
    IF (:NEW.PASSWORD IS NULL OR NOT (LENGTH(:NEW.PASSWORD) BETWEEN 8 AND 200)) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#PasswordValueRaise;
    END IF;

    --Validate Profile
    IF (:NEW.PROFILE IS NULL OR :NEW.PROFILE NOT IN ('ADMIN', 'USER', 'OPERATOR', 'ASSISTENT')) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#ProfileValueRaise;
    END IF;

    --Validate Email
    IF (:NEW.EMAIL IS NULL 
        OR 
        NOT (LENGTH(:NEW.EMAIL) BETWEEN 6 AND 500)
        OR 
        REGEXP_SUBSTR(:NEW.EMAIL, '[a-zA-Z0-9._%-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}') IS NULL) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#EmailValueRaise;
    END IF;
    SELECT COUNT(*) INTO v_COUNT FROM TICAN2.TB_USERS u
    WHERE
    u.EMAIL = :NEW.EMAIL;
    IF (v_COUNT != 0) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#EmailDuplicateRaise;
    END IF;

    --Validate Department
    IF (:NEW.DEPARTMENT IS NULL OR :NEW.DEPARTMENT NOT IN ('SALES', 'PRODUCTS', 'PROJECTS', 'MARKETING')) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#DepartmentValueRaise;
    END IF;

    --Validate Status
    IF (:NEW.STATUS IS NULL OR :NEW.STATUS NOT IN ('ACTIVE', 'LOCKED', 'BLOCKED', 'INACTIVE', 'DISABLED')) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#StatusValueRaise;
    END IF;

    --Validate UserCode
    SELECT COUNT(*) INTO v_COUNT FROM TICAN2.TB_USERS u
    WHERE
    u.LOGIN = :NEW.USER_CODE
    AND u.PROFILE = 'ADMIN' AND u.status =  'ACTIVE';
    IF (SQL%NOTFOUND OR v_COUNT = 0) THEN
        RAISE TICAN2.PKG_TICAN_DICTIONARY.Users#AdminNotFoundRaise;
    END IF;

    --Fix User Id
    SELECT TICAN2.USERS_SEQUENCE.NEXTVAL INTO v_ID FROM DUAL;
    :NEW.ID         := v_ID;

EXCEPTION
    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#LoginValueRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#LoginValueCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#LoginValueMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#PasswordValueRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#PasswordValueCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#PasswordValueMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#ProfileValueRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#ProfileValueCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#ProfileValueMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#EmailValueRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#EmailValueCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#EmailValueMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#EmailDuplicateRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#EmailDuplicateCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#EmailDuplicateMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#DepartmentValueRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#DepartmentValueCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#DepartmentValueMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#StatusValueRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#StatusValueCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#StatusValueMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#LoginDuplicateRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#LoginDuplicateCode,
                            TICAN2.PKG_TICAN_DICTIONARY.Users#LoginDuplicateMessage);

    WHEN TICAN2.PKG_TICAN_DICTIONARY.Users#AdminNotFoundRaise THEN
        RAISE_APPLICATION_ERROR(TICAN2.PKG_TICAN_DICTIONARY.Users#AdminNotFoundCode,
                                TICAN2.PKG_TICAN_DICTIONARY.Users#AdminNotFoundMessage);
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20999, 'TICAN2.TRG_USERS unexpected error: ' || SQLCODE || ' >> ' || SQLERRM);
END;
/
