/***********************************************************************/
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
/

CREATE TABLE TICAN2.TB_TEMPLATE_1 (
"ID"         NUMBER 
             GENERATED BY DEFAULT AS IDENTITY
            (START WITH 1 
             INCREMENT BY 1 
             MAXVALUE 9999999),
"DESCRIPTION"         VARCHAR2(100)           DEFAULT 'DESCRIPTION' NOT NULL,
CREATE_AT             TIMESTAMP(6) WITH LOCAL TIME ZONE default current_timestamp not null,
MODIFY_AT             TIMESTAMP(6) WITH LOCAL TIME ZONE default current_timestamp not null,
PRIMARY KEY (ID)
);
/
