/* Session settings */
SELECT * FROM NLS_SESSION_PARAMETERS;
SELECT * FROM NLS_DATABASE_PARAMETERS;
SELECT * FROM NLS_INSTANCE_PARAMETERS;
-- Change session settings
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SSXFF';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD/MM/YYYY HH24:MI:SSXFF';
ALTER SESSION SET NLS_TIME_TZ_FORMAT = 'HH24:MI:SSXFF TZR';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'DD/MM/YYYY HH24:MI:SSXFF TZR';
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

/* */
--DDL Data Definition Language (Objects)
--DML	Data Manipulation Language (Data)
--DCL Data Control Language (Security)
--DQL Data Query Language (Select)

/* Create User and grants to access/privileges */
CREATE USER TICAN
  IDENTIFIED BY tican
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  QUOTA UNLIMITED ON USERS;
-- 
GRANT CONNECT TO TICAN WITH ADMIN OPTION;
GRANT DBA TO TICAN WITH ADMIN OPTION;
-- 
GRANT CREATE MATERIALIZED VIEW TO TICAN WITH ADMIN OPTION;
GRANT CREATE TABLE TO TICAN WITH ADMIN OPTION;
GRANT GLOBAL QUERY REWRITE TO TICAN WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO TICAN WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO TICAN WITH ADMIN OPTION;

/* Create Table, Primary Key, Unique Value Fields, grants and synonym */
CREATE TABLE TICAN.TB_TEST1 (
ID           NUMBER        NOT NULL,
STATUS       VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
COD_GGREM    CHAR(18)      DEFAULT '000000000000000000' NOT NULL,
CONSTRAINT PK_ID PRIMARY KEY(ID),
CONSTRAINT UQ_1 UNIQUE (COD_GGREM)
)
TABLESPACE USERS
STORAGE (
INITIAL 64K 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED);
--

ALTER TABLE TICAN.TB_TEST1 ADD CONSTRAINT UQ_COD_GREEN UNIQUE (COD_GREEN);
--ALTER TABLE TICAN.TB_TEST1 ADD CONSTRAINT FK_NAME 
--FOREIGN KEY(FIELD) REFERENCES <OWNER.<TABLE>(FIELD);
--
COMMENT ON TABLE TICAN.TB_TEST1 IS 'TABLE TEST1';
COMMENT ON COLUMN TICAN.TB_TEST1.ID IS 'PRIMARY KEY';
--
GRANT ALL PRIVILEGES ON tican.tb_test1 TO SYS;
CREATE OR REPLACE PUBLIC SYNONYM TEST1 FOR TICAN.TB_TEST1;

/* MATERIALIZED VIEW */
CREATE MATERIALIZED VIEW "STUDY"."VW_MATERIALIZED_PRODUCTS" 
( "PK_PRODUCT", "STATUS", "COD_GGREM", "PRODUCT", 
  "ID_SUBSTANCE", "PRESENTATION", "TERAPY_CLASS", "RESTRICTION", 
  "TAG", "LABORATORY_NAME", "CNPJ", "REGISTRY_CODE", 
  "EAN1_CODE", "EAN2_CODE", "EAN3_CODE", "PRODUCT_TYPE", 
  "PRICE_RULE", "BASE_PRICE", "PRICE_ICMS_12", "PRICE_ICMS_17", 
  "PRICE_ICMS_18", "DT_INSERT", "DT_UPDATE", "USER_CODE", "SUBSTANCE", 
  "SUBSTANCE_STATUS")
  ORGANIZATION HEAP 
  PCTFREE 10 
  PCTUSED 40 
  INITRANS 1 
  MAXTRANS 255 
  NOCOMPRESS 
  LOGGING
  STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 
    FREELISTS 1 FREELIST 
    GROUPS 1 
    BUFFER_POOL DEFAULT 
    FLASH_CACHE DEFAULT 
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS 
  SELECT 
    P.*, 
    S.SUBSTANCE, 
    S.STATUS AS SUBSTANCE_STATUS
  FROM 
    STUDY.PRODUCTS P, STUDY.PRODUCTS_SUBSTANCES S
  WHERE 
    P.ID_SUBSTANCE = S.PK_SUBSTANCE
;

