--
CREATE TABLE TICAN.TB_PRODUCTS AS
(SELECT * FROM STUDY.PRODUCTS);

CREATE TABLE TICAN.TB_SUBSTANCES AS
(SELECT * FROM STUDY.PRODUCTS_SUBSTANCES);

ALTER TABLE "TICAN"."TB_PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK_1" PRIMARY KEY ("PK_PRODUCT");
CREATE UNIQUE INDEX "TICAN"."PROD_UNIQ_10" ON "TICAN"."TB_PRODUCTS" ("COD_GGREM", "PRODUCT");
ALTER TABLE "TICAN"."TB_PRODUCTS" ADD CONSTRAINT "PROD_UNIQ_10" UNIQUE ("COD_GGREM", "PRODUCT");

ALTER TABLE "TICAN"."TB_SUBSTANCES" ADD CONSTRAINT "SUBSTANCES_PK" PRIMARY KEY ("PK_SUBSTANCE");
CREATE UNIQUE INDEX "TICAN"."TB_SUBSTANCES_UNIQ_1" ON "TICAN"."TB_SUBSTANCES" ("SUBSTANCE");
--
--
CREATE OR REPLACE PUBLIC SYNONYM SUBSTANCES FOR TICAN.TB_SUBSTANCES;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCTS FOR TICAN.TB_PRODUCTS;
--
--
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN.TB_products TO tican_user, tican_user_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON TICAN.TB_substances TO tican_user, tican_user_service;
--
--
CREATE SEQUENCE TICAN.SQ_TICAN
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
CACHE 20;
--
GRANT SELECT ON TICAN.SQ_TICAN TO TICAN, TICAN_USER, TICAN_USER_SERVICE;
--
--
CREATE OR REPLACE TRIGGER TICAN.TRG_PRODUCTS_BEFORE_INSERT
BEFORE INSERT
   ON TICAN.TB_PRODUCTS
   FOR EACH ROW
DECLARE
   v_NEW_ID NUMBER;
BEGIN
   SELECT TICAN.SQ_TICAN.NEXTVAL INTO v_NEW_ID
   FROM DUAL;

   :NEW.PK_PRODUCT:= v_NEW_ID;

   :NEW.DT_INSERT:= SYSDATE;
   :NEW.DT_UPDATE:= SYSDATE;
   :NEW.USER_CODE:= 'tican_user';
   
END;
--
CREATE OR REPLACE TRIGGER TICAN.TRG_SUBSTANCES_BEFORE_INSERT
BEFORE INSERT
  ON TICAN.TB_SUBSTANCES
  FOR EACH ROW
DECLARE
v_NEW_ID NUMBER;
BEGIN
   SELECT TICAN.SQ_TICAN.NEXTVAL INTO v_NEW_ID
   FROM DUAL;
  
  :NEW.PK_SUBSTANCE:= v_NEW_ID;
  :NEW.STATUS:= 'inactive';
  
END;
--
--
CREATE OR REPLACE VIEW TICAN.VW_PRODUCTS_X_SUBSTANCES
AS
SELECT P.*, S.SUBSTANCE, S.STATUS AS SUBSTANCE_STATUS
FROM
TICAN.TB_PRODUCTS P
INNER JOIN TICAN.TB_SUBSTANCES S
ON P.ID_SUBSTANCE = S.PK_SUBSTANCE;
--
GRANT SELECT ON TICAN.VW_PRODUCTS_X_SUBSTANCES TO tican_user, tican_user_service;
--
CREATE OR REPLACE PUBLIC SYNONYM VW_PRODUCTS FOR TICAN.VW_PRODUCTS_X_SUBSTANCES; 
--
--
CREATE MATERIALIZED VIEW "TICAN"."VW_MATERIALIZED_PRODUCTS" 
( "PK_PRODUCT", "STATUS", "COD_GGREM", "PRODUCT", 
  "ID_SUBSTANCE", "PRESENTATION", "TERAPY_CLASS", "RESTRICTION", 
  "TAG", "LABORATORY_NAME", "CNPJ", "REGISTRY_CODE", 
  "EAN1_CODE", "EAN2_CODE", "EAN3_CODE", "PRODUCT_TYPE", 
  "PRICE_RULE", "BASE_PRICE", "PRICE_ICMS_12", "PRICE_ICMS_17", 
  "PRICE_ICMS_18", "DT_INSERT", "DT_UPDATE", "USER_CODE", "SUBSTANCE", 
  "SUBSTANCE_STATUS")
  ORGANIZATION HEAP 
  PCTFREE 10 
  PCTUSED 40 
  INITRANS 1 
  MAXTRANS 255 
  NOCOMPRESS 
  LOGGING
  STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 
    FREELISTS 1 FREELIST 
    GROUPS 1 
    BUFFER_POOL DEFAULT 
    FLASH_CACHE DEFAULT 
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS 
  SELECT 
    P.*, 
    S.SUBSTANCE, 
    S.STATUS AS SUBSTANCE_STATUS
  FROM 
    TICAN.TB_PRODUCTS P, TICAN.TB_SUBSTANCES S
  WHERE 
    P.ID_SUBSTANCE = S.PK_SUBSTANCE
;
--
--







