select * from OFB.TEST t

select to_char(t.timestamp4,'YYYY-MM-DD"T"HH:MI:SS.FF3"Z"') from OFB.TEST t

insert into ofb.test
  (date1, timestamp1, timestamp2, timestamp3)
values
  (SYSDATE, SYSDATE, SYSDATE, SYSDATE);


insert into ofb.test
  (date1, timestamp1, timestamp2, timestamp3)
values
  (current_timestamp, current_timestamp, current_timestamp, current_timestamp);
  
  
  SELECT CAST(SYSTIMESTAMP AT TIME ZONE 'UTC' AS DATE) FROM DUAL;
  
  
  SELECT (SYSTIMESTAMP(3) AT TIME ZONE 'UTC') AS dt FROM DUAL;
  
  2025-05-21 16:2i:52
  

GRANT SELECT ANY SEQUENCE, EXECUTE ANY VIEW, SELECT ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE, UPDATE ANY TABLE TO OFB;
GRANT SELECT ANY SEQUENCE, SELECT ANY VIEW, SELECT ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE, UPDATE ANY TABLE TO OFB_OWNER;
GRANT SELECT ANY SEQUENCE, SELECT ANY VIEW, SELECT ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE, UPDATE ANY TABLE TO OFB_USER;

grant ALL any table on schema OFB to ofb;


GRANT ALL ON SCHEMA OFB TO ofb
   WITH GRANT OPTION; 
   
SELECT DISTINCT OWNER, OBJECT_NAME 
  FROM ALL_OBJECTS
 WHERE OBJECT_TYPE = 'TABLE'
   AND OWNER = 'OFB'
