apiVersion: v1
kind: Service
metadata:
  name: db-mysql-svc
  labels:
    app: db-mysql-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.207
  selector:
    app: db-mysql-pod
  ports:
    - port: 3306
      targetPort: 31306
  