apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-business-pvc
  labels:
    app: products-business-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
