apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: products-business-services
  labels:
    app: products-business-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-business-pod
  template:
    metadata:
      name: products-business-pod
      labels:
        app: products-business-pod
    spec:
      containers:
        - name: products-business-container
          image: fras200627/products-business:1.0.0
          ports:
            - containerPort: 6010
          envFrom:
            - configMapRef:
                name: config-map-defaults
            - configMapRef:
                name: products-business-cmap  
          volumeMounts:
            - name: products-business-persist
              mountPath: /default/products-business-pvc
      volumes:
        - name: products-business-persist
          persistentVolumeClaim:
            claimName: products-business-pvc
  serviceName: products-business-services-stateful
    