apiVersion: v1
kind: Service
metadata:
  name: products-business-nodeport
  labels:
    app: products-business-nodeport
spec:
  type: NodePort
  ports:
    - port: 6010
      nodePort: 31010
  selector:
    app: products-business-pod
