apiVersion: v1
kind: Service
metadata:
  name: tican-discovery-services-svc
  labels:
    app: tican-discovery-services-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.101
  selector:
    app: tican-discovery-services-pod
  ports:
    - port: 3000
      targetPort: 30000
      
    
  