apiVersion: v1
kind: ConfigMap
metadata:
  name: tican-oauth2-users-domain-cmap
  labels:
    app: tican-oauth2-users-domain-cmap
data:
  OAUTH2_CLIENTS_domain_REPLICAS : "1"
  SPRING.PROFILES.ACTIVE: "k8s"
  SERVICE_AUDIT_EXPOSE_PORT: "30081"
  PROFILE_ACTIVE: "k8s"
  API_LOGGING_LEVEL: "info"
  API_SWAGGER_ENABLE: "false"
  AUDIT_SERVICES_REPLICAS: "3"

