apiVersion: v1
kind: Service
metadata:
  name: tican-oauth2-users-domain-svc
  labels:
    app: tican-oauth2-users-domain-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.129
  selector:
    app: tican-oauth2-users-domain-pod
  ports:
    - port: 3081
      targetPort: 30081
      
    
  