apiVersion: v1
kind: Service
metadata:
  name: tican-oauth2-users-domain-nodeport
  labels:
    app: tican-oauth2-users-domain-nodeport
spec:
  type: NodePort
  clusterIP: 10.152.183.131
  ports:
    - port: 3081
      nodePort: 30081
  selector:
    app: tican-oauth2-users-domain-pod

