apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth2-users-domain-pvc
  labels:
    app: oauth2-users-domain-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
