apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-pvc
  labels:
    app: db-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
      
