apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-services-pvc
  labels:
    app: audit-services-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
