apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: audit-services
  labels:
    app: audit-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-services-pod
  template:
    metadata:
      name: audit-services-pod
      labels:
        app: audit-services-pod
    spec:
      containers:
        - name: audit-services-container
          image: fras200627/audit-services:1.0.0
          ports:
            - containerPort: 6011
          envFrom:
            - configMapRef:
                name: config-map-defaults
            - configMapRef:
                name: audit-services-cmap  
          volumeMounts:
            - name: audit-services-persist
              mountPath: /default/audit-services-pvc
      volumes:
        - name: audit-services-persist
          persistentVolumeClaim:
            claimName: audit-services-pvc
  serviceName: audit-services-stateful
    