apiVersion: v1
kind: Service
metadata:
  name: audit-services-svc
  labels:
    app: audit-services-svc
spec:
  type: ClusterIP
  selector:
    app: audit-services-pod
  ports:
    - port: 6011
      targetPort: 6011
