--prompt Importing table OFB.RESOURCES_STATUS...
--set feedback off
--set define off

insert into OFB.RESOURCES_STATUS (RESOURCESTATUSID, STATUS, SUMMARY, CREATE_AT, MODIFY_AT, USER_CODE)
values (1, 'Available', 'Disponível', '22/05/25 11:39:46,914 UTC', '22/05/25 11:39:46,914 UTC', 'USER_ADMIN');

insert into OFB.RESOURCES_STATUS (RESOURCESTATUSID, STATUS, SUMMARY, CREATE_AT, MODIFY_AT, USER_CODE)
values (2, 'Unavailable', 'Indisponível', '22/05/25 11:39:46,929 UTC', '22/05/25 11:39:46,929 UTC', 'USER_ADMIN');

insert into OFB.RESOURCES_STATUS (RESOURCESTATUSID, STATUS, SUMMARY, CREATE_AT, MODIFY_AT, USER_CODE)
values (3, 'Temporarily Unavailable', 'Temporariamente Indisponível', '22/05/25 11:39:46,950 UTC', '22/05/25 11:39:46,950 UTC', 'USER_ADMIN');

insert into OFB.RESOURCES_STATUS (RESOURCESTATUSID, STATUS, SUMMARY, CREATE_AT, MODIFY_AT, USER_CODE)
values (4, 'Pending Authorisation', 'Pendente de Autorização', '22/05/25 11:39:46,966 UTC', '22/05/25 11:39:46,966 UTC', 'USER_ADMIN');

commit;

--prompt Importing table OFB.RESOURCES_TYPES...
--set feedback off
--set define off

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (2, 'RESOURCES', 'AVAILABLE', 'Resources', 'Tipo principal e obrigatório para todos os outros types', '22/05/25 11:36:07,176 UTC', '22/05/25 11:36:07,176 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (3, 'CUSTOMER', 'AVAILABLE', 'Customers', 'Informações de dados cadastrais', '22/05/25 11:36:07,204 UTC', '22/05/25 11:36:07,204 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (4, 'ACCOUNT', 'AVAILABLE', 'Contas', 'Conta de depósito à vista, poupança ou pagamento pré-paga', '22/05/25 11:36:07,235 UTC', '22/05/25 11:36:07,235 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (5, 'CREDIT_CARD_ACCOUNT', 'UNAVAILABLE', 'Cartões', 'Conta de pagamento pós-paga (Cartão de Crédito)', '22/05/25 11:36:07,267 UTC', '22/05/25 11:36:07,267 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (6, 'LOAN', 'UNAVAILABLE', 'Empréstimos', 'Empréstimo', '22/05/25 11:36:07,310 UTC', '22/05/25 11:36:07,310 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (7, 'FINANCING', 'UNAVAILABLE', 'Financiamentos', 'Financiamento', '22/05/25 11:36:07,347 UTC', '22/05/25 11:36:07,347 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (8, 'UNARRANGED_ACCOUNT_OVERDRAFT', 'UNAVAILABLE', 'Cheque Especial', 'Cheque Especial', '22/05/25 11:36:07,379 UTC', '22/05/25 11:36:07,379 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (9, 'INVOICE_FINANCING', 'UNAVAILABLE', 'Financiamentos de Faturas', 'Financiamento de Fatura', '22/05/25 11:36:07,410 UTC', '22/05/25 11:36:07,410 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (10, 'BANK_FIXED_INCOME', 'UNAVAILABLE', 'Renda-Fixa', 'Renda Fixa Bancária', '22/05/25 11:36:07,447 UTC', '22/05/25 11:36:07,447 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (11, 'CREDIT_FIXED_INCOME', 'UNAVAILABLE', 'Renda-Fixa Crédito', 'Renda Fixa Crédito', '22/05/25 11:36:07,474 UTC', '22/05/25 11:36:07,474 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (12, 'VARIABLE_INCOME', 'UNAVAILABLE', 'Renda-Variável', 'Renda Variável', '22/05/25 11:36:07,505 UTC', '22/05/25 11:36:07,505 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (13, 'TREASURE_TITLE', 'UNAVAILABLE', 'Tesouro Direto', 'Título do Tesouro Direto', '22/05/25 11:36:07,553 UTC', '22/05/25 11:36:07,553 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (14, 'FUND', 'UNAVAILABLE', 'Fundos', 'Fundo de Investimento', '22/05/25 11:36:07,595 UTC', '22/05/25 11:36:07,595 UTC', 'OFB_ADMIN');

insert into OFB.RESOURCES_TYPES (RESOURCETYPEID, TYPE, STATUS, SUMMARY, DESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (15, 'EXCHANGE', 'UNAVAILABLE', 'Câmbio', 'Câmbio', '22/05/25 11:36:07,633 UTC', '22/05/25 11:36:07,633 UTC', 'OFB_ADMIN');

commit;

--prompt Importing table OFB.CONSENTS_STATUS...
--set feedback off
--set define off

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (80, 0, 'AWAITING_AUTHORISATION', 1, 'start of permission', 'start of permission', '22/05/25 11:39:19,554 UTC', '22/05/25 11:39:19,554 UTC', 'USER_ADMIN');

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (81, 1, 'AUTHORISED', 1, 'permission confirmed', 'permission confirmed', '22/05/25 11:39:19,570 UTC', '22/05/25 11:39:19,570 UTC', 'USER_ADMIN');

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (82, 2, 'REJECTED', 1, 'permission rejected - approval time expired', 'permission rejected - approval time expired', '22/05/25 11:39:19,602 UTC', '22/05/25 11:39:19,602 UTC', 'USER_ADMIN');

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (83, 2, 'REJECTED', 2, 'permission rejected - consent expiration date', 'permission rejected - consent expiration date', '22/05/25 11:39:19,617 UTC', '22/05/25 11:39:19,617 UTC', 'USER_ADMIN');

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (84, 2, 'REJECTED', 3, 'permission rejected - explicit revocation requested by client', 'permission rejected - explicit revocation requested by client', '22/05/25 11:39:19,639 UTC', '22/05/25 11:39:19,639 UTC', 'USER_ADMIN');

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (85, 99, 'REQUEST_IN_PROGRESS', 0, 'request in progress - creation of a new consent in progress', 'request in progress - creation of a new consent in progress', '08/07/25 11:46:09,825 -03:00', '08/07/25 11:46:09,825 -03:00', 'USER_ADMIN');

insert into OFB.CONSENTS_STATUS (CONSENTSTATUSID, CONSENTSTATUSCONTROLID, STATUS, STATUSSTEP, STATUSREASON, STATUSDESCRIPTION, CREATE_AT, MODIFY_AT, USER_CODE)
values (86, 99, 'REQUEST_CANCELLED', 1, 'request cancelled - creation of a new consent cancelled', 'request cancelled - creation of a new consent cancelled', '08/07/25 11:48:01,658 -03:00', '08/07/25 11:48:01,658 -03:00', 'USER_ADMIN');

commit;

--prompt Importing table OFB.RESOURCES_PERMISSIONS...
--set feedback off
--set define off

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (380, 5, 4, 'Cartão de Crédito', 31, 'Cartões-Limites', 1, 'CREDIT_CARDS_ACCOUNTS_LIMITS_READ', 'true', 'Por recurso', '25/06/25 14:06:57,307 -03:00', '25/06/25 14:06:57,307 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (382, 5, 4, 'Cartão de Crédito', 31, 'Cartões-Faturas', 3, 'CREDIT_CARDS_ACCOUNTS_BILLS_READ', 'true', 'Por recurso', '25/06/25 14:06:57,401 -03:00', '25/06/25 14:06:57,401 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (383, 5, 4, 'Cartão de Crédito', 31, 'Cartões-Faturas Lançamentos', 4, 'CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ', 'true', 'Por recurso', '25/06/25 14:06:57,444 -03:00', '25/06/25 14:06:57,444 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (385, 6, 5, 'Operações de Crédito', 31, 'Empréstimos-Garantias', 3, 'LOANS_WARRANTIES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,534 -03:00', '25/06/25 14:06:57,534 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (387, 6, 5, 'Operações de Crédito', 31, 'Empréstimos-Pagamentos Efetuados', 1, 'LOANS_PAYMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,632 -03:00', '25/06/25 14:06:57,632 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (388, 7, 6, 'Operações de Crédito', 30, 'Financiamentos', 0, 'FINANCINGS_READ', 'false', 'Por agrupamento de produtos', '25/06/25 14:06:57,680 -03:00', '25/06/25 14:06:57,680 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-CONTROL', 'Exigido ser informado caso um ou mais itens do grupo estejam nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (389, 7, 6, 'Operações de Crédito', 31, 'Financiamentos-Garantias', 1, 'FINANCINGS_WARRANTIES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,729 -03:00', '25/06/25 14:06:57,729 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (390, 7, 6, 'Operações de Crédito', 31, 'Financiamentos-Parcelas Agendadas', 3, 'FINANCINGS_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,770 -03:00', '25/06/25 14:06:57,770 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (392, 8, 7, 'Operações de Crédito', 30, 'Cheque-Especial', 0, 'UNARRANGED_ACCOUNTS_OVERDRAFT_READ', 'false', 'Por agrupamento de produtos', '25/06/25 14:06:57,860 -03:00', '25/06/25 14:06:57,860 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-CONTROL', 'Exigido ser informado caso um ou mais itens do grupo estejam nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (393, 8, 7, 'Operações de Crédito', 31, 'Cheque-Especial-Garantias', 2, 'UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,904 -03:00', '25/06/25 14:06:57,904 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (394, 8, 7, 'Operações de Crédito', 31, 'Cheque-Especial- Saldo Negativo', 1, 'UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,948 -03:00', '25/06/25 14:06:57,948 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (397, 9, 8, 'Operações de Crédito', 31, 'Financiamentos-Faturas  - Garantias', 1, 'INVOICE_FINANCINGS_WARRANTIES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,090 -03:00', '25/06/25 14:06:58,090 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (398, 9, 8, 'Operações de Crédito', 31, 'Financiamentos-Faturas - Agendamentos Programados', 2, 'INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,138 -03:00', '25/06/25 14:06:58,138 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (400, 10, 9, 'Investimento', 99, 'Investimentos Renda-Fixa', 0, 'BANK_FIXED_INCOMES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,229 -03:00', '25/06/25 14:06:58,229 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (401, 11, 10, 'Investimento', 99, 'Investimentos Renda-Fixa Crédito', 0, 'CREDIT_FIXED_INCOMES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,273 -03:00', '25/06/25 14:06:58,273 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (402, 14, 13, 'Investimento', 99, 'Investimentos-Fundos', 0, 'FUNDS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,316 -03:00', '25/06/25 14:06:58,316 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (403, 12, 11, 'Investimento', 99, 'Investimentos Renda-Variável', 0, 'VARIABLE_INCOMES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,363 -03:00', '25/06/25 14:06:58,363 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (404, 13, 12, 'Investimento', 99, 'Investimentos-Títulos do Tesouro', 0, 'TREASURE_TITLES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,395 -03:00', '25/06/25 14:06:58,395 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (405, 15, 14, 'Cãmbio', 99, 'Operações de Cãmbio', 0, 'EXCHANGES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,439 -03:00', '25/06/25 14:06:58,439 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (406, 15, 14, 'Cãmbio', 99, 'Operações de Cãmbio - Detalhes da Operação', 1, 'EXCHANGES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,483 -03:00', '25/06/25 14:06:58,483 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (407, 15, 14, 'Cãmbio', 99, 'Operações de Cãmbio - Eventos', 2, 'EXCHANGES_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,527 -03:00', '25/06/25 14:06:58,527 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'UNIQUE', 'Opcional único: não esta vinculado a nenhum *GROUP-OBRIGATORY*');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (370, 2, 0, 'Resources', 0, 'Informações sobre resources', 0, 'RESOURCES_READ', 'false', 'Por recurso/grupo', '25/06/25 14:06:56,862 -03:00', '25/06/25 14:06:56,862 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'Y', 'MANDATORY', 'Exigido ser informado nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (371, 3, 1, 'Cadastro PF', 10, 'Cadastro PF - Dados Cadastrais', 0, 'CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ', 'true', 'Por recurso', '25/06/25 14:06:56,916 -03:00', '25/06/25 14:06:56,916 -03:00', 'USER_ADMIN', 'AVAILABLE', 'N', 'Y', 'MANDATORY', 'Customers-PF: Exigido ser informado nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (372, 3, 1, 'Cadastro PF', 11, 'Cadastro PF - Informações Complementares', 1, 'CUSTOMERS_PERSONAL_ADITTIONALINFO_READ', 'true', 'Por recurso', '25/06/25 14:06:56,960 -03:00', '25/06/25 14:06:56,960 -03:00', 'USER_ADMIN', 'AVAILABLE', 'N', 'Y', 'MANDATORY-OPTIONAL', 'Customers-PF: Opcional nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (373, 3, 2, 'Cadastro PJ', 20, 'Cadastro PJ - Dados Cadastrais', 0, 'CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ', 'true', 'Por recurso', '25/06/25 14:06:56,999 -03:00', '25/06/25 14:06:56,999 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'N', 'MANDATORY', 'Customers-PJ: Exigido ser informado nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (374, 3, 2, 'Cadastro PJ', 21, 'Cadastro PJ - Informações Complementares', 1, 'CUSTOMERS_BUSINESS_ADITTIONALINFO_READ', 'true', 'Por recurso', '25/06/25 14:06:57,038 -03:00', '25/06/25 14:06:57,038 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'N', 'MANDATORY-OPTIONAL', 'Customers-PJ: Opcional nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (377, 4, 3, 'Contas', 31, 'Contas-Limites', 2, 'ACCOUNTS_OVERDRAFT_LIMITS_READ', 'true', 'Por recurso', '25/06/25 14:06:57,149 -03:00', '25/06/25 14:06:57,149 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (378, 4, 3, 'Contas', 31, 'Contas-Extratos', 3, 'ACCOUNTS_TRANSACTIONS_READ', 'true', 'Por recurso', '25/06/25 14:06:57,207 -03:00', '25/06/25 14:06:57,207 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (386, 6, 5, 'Operações de Crédito', 31, 'Empréstimos-Parcelas Agendadas', 2, 'LOANS_SCHEDULED_INSTALMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,581 -03:00', '25/06/25 14:06:57,581 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (391, 7, 6, 'Operações de Crédito', 31, 'Financiamentos-Pagamentos Efetuados', 2, 'FINANCINGS_PAYMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,815 -03:00', '25/06/25 14:06:57,815 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (395, 8, 7, 'Operações de Crédito', 31, 'Cheque-Especial-Pagamentos Programados', 3, 'UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:57,984 -03:00', '25/06/25 14:06:57,984 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (396, 9, 8, 'Operações de Crédito', 30, 'Financiamentos-Faturas', 0, 'INVOICE_FINANCINGS_READ', 'false', 'Por agrupamento de produtos', '25/06/25 14:06:58,039 -03:00', '25/06/25 14:06:58,039 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-CONTROL', 'Exigido ser informado caso um ou mais itens do grupo estejam nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (399, 9, 8, 'Operações de Crédito', 31, 'Financiamentos-Faturas - Pagamentos Efetuados', 3, 'INVOICE_FINANCINGS_PAYMENTS_READ', 'true', 'Por agrupamento de produtos', '25/06/25 14:06:58,187 -03:00', '25/06/25 14:06:58,187 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (375, 4, 3, 'Contas', 30, 'Contas', 0, 'ACCOUNTS_READ', 'false', 'Por recurso', '25/06/25 14:06:57,071 -03:00', '25/06/25 14:06:57,071 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'Y', 'GROUP-CONTROL', 'Exigido ser informado caso um ou mais itens do grupo estejam nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (376, 4, 3, 'Contas', 31, 'Contas-Saldos', 1, 'ACCOUNTS_BALANCES_READ', 'true', 'Por recurso', '25/06/25 14:06:57,115 -03:00', '25/06/25 14:06:57,115 -03:00', 'USER_ADMIN', 'AVAILABLE', 'Y', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (379, 5, 4, 'Cartão de Crédito', 30, 'Cartões', 0, 'CREDIT_CARDS_ACCOUNTS_READ', 'false', 'Por recurso', '25/06/25 14:06:57,255 -03:00', '25/06/25 14:06:57,255 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-CONTROL', 'Exigido ser informado caso um ou mais itens do grupo estejam nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (381, 5, 4, 'Cartão de Crédito', 31, 'Cartões-Transações', 2, 'CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ', 'true', 'Por recurso', '25/06/25 14:06:57,355 -03:00', '25/06/25 14:06:57,355 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'N', 'Y', 'GROUP-ITEM', 'Opcional mas o seu correspondente *GROUP-OBRIGATORY* deve estar nas permissões de um novo consentimento');

insert into OFB.RESOURCES_PERMISSIONS (RESOURCEPERMISSIONID, RESOURCETYPEID, PERMISSIONCATEGORYID, PERMISSIONCATEGORY, PERMISSIONEVENTGROUPID, PERMISSIONCATEGORYGROUP, PERMISSIONCATEGORYORDER, PERMISSION, ISPERMISSIONEVENT, PERMISSIONGROUPING, CREATE_AT, MODIFY_AT, USER_CODE, RESOURCESTATUS, RESOURCEISAVAILABLEBUSINESS, RESOURCEISAVAILABLEPERSONAL, PERMISSIONCONTROL, PERMISSIONCONTROLDESCRIPTION)
values (384, 6, 5, 'Operações de Crédito', 30, 'Empréstimos', 0, 'LOANS_READ', 'false', 'Por agrupamento de produtos', '25/06/25 14:06:57,488 -03:00', '25/06/25 14:06:57,488 -03:00', 'USER_ADMIN', 'UNAVAILABLE', 'Y', 'Y', 'GROUP-CONTROL', 'Exigido ser informado caso um ou mais itens do grupo estejam nas permissões de um novo consentimento');

commit;

