# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: db-mysql-pod
  labels:
    app: db-mysql-pod
spec:
  containers:
    - name: db-mysql-container
      image: 'fras200627/db-tican-mysql:210.0'
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-mysql-cmap