# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: mq-rabbit-pod
  labels:
    app: mq-rabbit-pod
spec:
  containers:
    - name: mq-rabbit-container
      image: 'rabbitmq:3-management'
      volumeMounts:
        - mountPath: /rabbitmqdata
          name: volumerabbitmq
      ports:
        - containerPort: 5672
          name: service1
        - containerPort: 5673
          name: service2
        - containerPort: 15672
          name: dashboard
      envFrom:
        - configMapRef:
            name: mq-rabbit-cmap
  volumes:
    - name: volumerabbitmq
      hostPath: 
        path: /C/kubernetes/volumes
        type: Directory
      