# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mq-rabbit-nodeport
  labels:
    app: mq-rabbit-nodeport
spec:
  type: NodePort
  ports:
    - port: 15672
      nodePort: 31672
  selector:
    app: mq-rabbit-pod
