apiVersion: v1
kind: Service
metadata:
  name: mq-rabbit-svc
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: service1
    - port: 5673
      targetPort: 5672
      name: service2
  selector:
    app: mq-rabbit-pod
    