# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: tican-eureka-nodeport
  labels:
    app: tican-eureka-nodeport
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 31000
  selector:
    app: tican-eureka-pod
