apiVersion: v1
kind: Service
metadata:
  name: oauth2-users-domain-svc
  labels:
    app: oauth2-users-domain-svc
spec:
  type: ClusterIP
  selector:
    app: oauth2-users-domain-pod
  ports:
    - port: 6004
      targetPort: 6004
