apiVersion: v1
kind: ConfigMap
metadata:
  name: tican-api-gateway-cmap
  labels:
    app: tican-api-gateway-cmap
data:
  SPRING.PROFILES.ACTIVE        : "k8s"
  SERVICE_DISCOVERY_EXPOSE_PORT : "30001"
  PROFILE_ACTIVE                : "k8s"
  API_LOGGING_LEVEL             : "info"

