apiVersion: v1
kind: Service
metadata:
  name: tican-api-gateway-svc
  labels:
    app: tican-api-gateway-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.105
  selector:
    app: tican-api-gateway-pod
  ports:
    - port: 3001
      targetPort: 30001
      
    
  