version: '3.9'

services:
  #   MySQL 8.0 Service ###############################################
  db-mysql-svc:
    image: ${MYSQL_IMAGE}
    hostname: ${MYSQL_HOST_NAME}
    domainname: ${DOCKER_DOMAIN_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
    networks:
      ofb-services-network:
        ipv4_address: ${MYSQL_HOST_IP}
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    expose:
      - ${MYSQL_EXPOSE_PORT}
    volumes:
      - db-mysql-data:${MYSQL_DATA_VOLUME}
      - db-mysql-backup:${MYSQL_BACKUP_VOLUME}  

  # Oracle Xe 21.c Service ##########################################
  db-oracle-svc:
    image: ${ORACLEXE_IMAGE}
    hostname: ${ORACLEXE_HOST_NAME}
    domainname: ${DOCKER_DOMAIN_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      ORACLE_PASSWORD: ${ORACLE_SYS_PWD}
    networks:
      ofb-services-network:
        ipv4_address: ${ORACLE_HOST_IP}
    ports:
      - ${ORACLE_EXTERNAL_PORT}:${ORACLE_INTERNAL_PORT}
    expose:
      - ${ORACLE_EXPOSE_PORT}
    volumes:
      - db-oracle-data:${ORACLE_DATA_VOLUME}
      - db-oracle-backup:${ORACLE_BACKUP_VOLUME}
    healthcheck:
      test: ['CMD', 'sqlplus', '-L', 'sys/tican@//db-oracle-services:1521/XE as sysdba', '@healthcheck.sql']
      interval: '30s'
      timeout: '10s'
      retries: 5
      
  # Rabbit MQ 3.12.11 Service ##########################################
  mq-rabbit-svc:
    image: ${RABBITMQ_IMAGE}
    hostname: ${RABBITMQ_HOST_NAME}
    domainname: ${DOCKER_DOMAIN_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PWD}
    networks:
      ofb-services-network:
        ipv4_address: ${RABBITMQ_HOST_IP}
    ports:
#      - ${RABBITMQ_SERVICE_EXPOSE_PORT}:${RABBITMQ_SERVICE_INTERNAL_PORT}
#      - ${RABBITMQ_CLUSTER_EXPOSE_PORT}:${RABBITMQ_CLUSTER_INTERNAL_PORT}
      - ${RABBITMQ_DASHBOARD_EXTERNAL_PORT}:${RABBITMQ_DASHBOARD_INTERNAL_PORT}
#    expose:
#      - ${RABBITMQ_SERVICE_EXPOSE_PORT}
#      - ${RABBITMQ_CLUSTER_EXPOSE_PORT}
#      - ${RABBITMQ_DASHBOARD_EXPOSE_PORT}
    volumes:
      - mq-rabbit-data:${RABBITMQ_DATA_VOLUME}
      - mq-rabbit-backup:${RABBITMQ_BACKUP_VOLUME}
      
  # API Gateway Service ###############################################
  ofb-discovery-services:
    image: ${DISCOVERY_SERVICES_IMAGE}
    hostname: ${DISCOVERY_SERVICES_HOST_NAME}
    domainname: ${DOCKER_DOMAIN_NAME}
#    depends_on:
#      - db-tican-mysql
#      - db-tican-oracle
#      - tican-rabbit-mq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      spring.profiles.active: ${PROFILE_ACTIVE}
    networks:
      ofb-services-network:
        ipv4_address: ${DISCOVERY_SERVICES_HOST_IP}
    ports:
      - ${DISCOVERY_SERVICES_EXTERNAL_PORT}:${DISCOVERY_SERVICES_INTERNAL_PORT}
    expose:
      - ${DISCOVERY_SERVICES_EXPOSE_PORT}
    volumes:
      - discovery-services-data:${DISCOVERY_SERVICES_DATA_VOLUME}
      - discovery-services-backup:${DISCOVERY_SERVICES_BACKUP_VOLUME}

  # API Gateway Service ###############################################
  ofb-api-gateway:
    image: ${API_GATEWAY_IMAGE}
    hostname: ${API_GATEWAY_HOST_NAME}
    domainname: ${DOCKER_DOMAIN_NAME}
    depends_on:
      - ${DISCOVERY_SERVICES_HOST_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 6
        window: 120s
    environment:
      spring.profiles.active: ${PROFILE_ACTIVE}
    networks:
      ofb-services-network:
        ipv4_address: ${API_GATEWAY_HOST_IP}
    ports:
      - ${API_GATEWAY_EXTERNAL_PORT}:${API_GATEWAY_INTERNAL_PORT}
    expose:
      - ${API_GATEWAY_EXPOSE_PORT}
    volumes:
      - api-gateway-data:${API_GATEWAY_DATA_VOLUME}
      - api-gateway-backup:${API_GATEWAY_BACKUP_VOLUME}

#configs:

#secrets:

volumes:
  db-mysql-data:
  db-mysql-backup:
  db-oracle-data:
  db-oracle-backup:
  mq-rabbit-data:
  mq-rabbit-backup:
  discovery-services-data:
  discovery-services-backup:
  api-gateway-data:
  api-gateway-backup:
networks:
  ofb-services-network:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.1.0/24
          gateway: 10.0.1.254
