# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-pod-cmap
  labels:
    app: nginx-pod-cmap
data:
  SPRING.PROFILES.ACTIVE        : "dev"
  SERVICE_DISCOVERY_EXPOSE_PORT : "30083"
  PROFILE_ACTIVE                : "dev"
  API_LOGGING_LEVEL             : "trace"

