# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-pod-svc
  labels:
    app: nginx-pod-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-pod
  ports:
    - port: 30083
      targetPort: 80
      
    
  