# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-pod-nodeport
  labels:
    app: nginx-pod-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30083
  selector:
    app: nginx-pod
