spring:
  application:
    name: ofb-audit-extends-consents-api
  session:
    store-type: jdbc
  security:
    filter:
      dispatcher-types: request
  jpa:
    properties:
      hibernate:
        format_sql: true    
    show-sql: ${API_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${API_HIBERNATE_DDL_AUTO:none}
server:
  error:
    include-stacktrace: never

jwt:
  issuer: banco-tcn-openfinance-brasil
  private:
    key: classpath:keystore/app.private.key
  public:
    key: classpath:keystore/app.public.key


# Custom properties
app:
  listOfServers: #server item: id, description, url
    - 0, 'Tican Server at LOCAL execution', http://localhost/3000
    - 1, 'Tican Server at DOCKER execution', http://localhost/5000
    - 2, 'Tican Server at K8S execution', http://localhost/7000
eureka:
  instance:
    hostname: ${DISCOVERY_SERVICES_APP_NAME:ofb-discovery-services}
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
resilience4j:
  circuitBreaker:
    instances:
      authServerDomain:
        waitDurationInOpenState: 50s
        minimumNumberOfCalls: 2
        slidingWindowSize: 3
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

# Swagger page: http://localhost:3051/swagger-ui
springdoc:
  api-docs:
    enabled: true
  packagesToScan: com.ofb
  pathsToMatch: /**
  swagger-ui:
    enabled: true
    path: /swagger-ui
    disable-swagger-default-url: true
    show-common-extensions: true
    show-extensions: true
    operationsSorter: alpha
    tagsSorter: alpha

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/ofb?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PWD:root}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
amqp:
  ofb:
    exchange-direct: "ofb.exchange.direct"
    audit:
      http-requests:
        queue: "ofb.audit.http.requests"
        routing-key: "audit.http.requests"
      consents-authorization:
        queue: "ofb.audit.consents.authorization"
        routing-key: "audit.consents.auth"
      consents-cancellation:
        queue: "ofb.audit.consents.cancellation"
        routing-key: "audit.consents.cancel"
      consents-revoke:
        queue: "ofb.audit.consents.revoke"
        routing-key: "audit.consents.revoke"
      consents-extends:
        queue: "ofb.audit.consents.extends"
        routing-key: "audit.consents.extends"
    consents:
      authorization:
        queue: "ofb.consents.authorization"
        routing-key: "exec.consents.auth"
      cancellation:
        queue: "ofb.consents.cancellation"
        routing-key: "exec.consents.cancel"
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3051 # set to "0" if you want eureka-server to determine a port dynamically
---
spring:
  config:
    activate:
      on-profile: docker
  security:
    auth:
      provider-uri: http://10.0.1.2:3001/ofb-authentication-server
  datasource:
    url: jdbc:mysql://10.0.1.100:3306/ofb?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PWD:ofb}
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.1:3000/eureka
amqp:
  ofb:
    exchange-direct: "ofb.exchange.direct"
    audit:
      http-requests:
        queue: "ofb.audit.http.requests"
        routing-key: "audit.http.requests"
      consents-authorization:
        queue: "ofb.audit.consents.authorization"
        routing-key: "audit.consents.auth"
      consents-cancellation:
        queue: "ofb.audit.consents.cancellation"
        routing-key: "audit.consents.cancel"
      consents-revoke:
        queue: "ofb.audit.consents.revoke"
        routing-key: "audit.consents.revoke"
      consents-extends:
        queue: "ofb.audit.consents.extends"
        routing-key: "audit.consents.extends"
    consents:
      authorization:
        queue: "ofb.consents.authorization"
        routing-key: "exec.consents.auth"
      cancellation:
        queue: "ofb.consents.cancellation"
        routing-key: "exec.consents.cancel"
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3051 # set to "0" if you want eureka-server to determine a port dynamically
---
spring:
  config:
    activate:
      on-profile: k8s
  rabbitmq:
    host: ${RABBITMQ_CLUSTERIP_SVC:10.152.183.205}
    port: ${RABBITMQ_SERVICE_INTERNAL_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:ofb}
    password: ${RABBITMQ_DEFAULT_PASS:ofb}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://10.152.183.107:3001/ofb-authentication-server
  datasource:
    url: jdbc:mysql://10.152.183.209:3306/ofb?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PWD:root}
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.152.183.103:3000/eureka
amqp:
  ofb:
    exchange-direct: "ofb.exchange.direct"
    audit:
      http-requests:
        queue: "ofb.audit.http.requests"
        routing-key: "audit.http.requests"
      consents-authorization:
        queue: "ofb.audit.consents.authorization"
        routing-key: "audit.consents.auth"
      consents-cancellation:
        queue: "ofb.audit.consents.cancellation"
        routing-key: "audit.consents.cancel"
      consents-revoke:
        queue: "ofb.audit.consents.revoke"
        routing-key: "audit.consents.revoke"
      consents-extends:
        queue: "ofb.audit.consents.extends"
        routing-key: "audit.consents.extends"
    consents:
      authorization:
        queue: "ofb.consents.authorization"
        routing-key: "exec.consents.auth"
      cancellation:
        queue: "ofb.consents.cancellation"
        routing-key: "exec.consents.cancel"
# The port can be fixed to "0" so that eureka-server determines a port dynamically
# but in this case access to Swagger-UI will not work
server:
  port: 3051 # set to "0" if you want eureka-server to determine a port dynamically
