apiVersion: v1
kind: Pod
metadata:
  name: tican-authentication-server-pod
  labels:
    app: tican-authentication-server-pod
spec:
  containers:
    - name: tican-authentication-server-container
      image: fras200627/tican-authentication-server:1.0.1-openapi
      ports:
        - containerPort: 3031
      envFrom:
        - configMapRef:
            name: config-map-defaults
        - configMapRef:
            name: tican-authentication-server-cmap
#      volumeMounts:
#        - name: auth-server-persist
#          mountPath: /default/auth-server-pvc
#  volumes:
#    - name: auth-server-persist
#      persistentVolumeClaim:
#        claimName: auth-server-pvc