apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-defaults
  labels:
    app: config-map-defaults
data:
  # Default Settings
  API_NAMESPACE                       : "tican-services"
  API_NAMESPACE_TITLE                 : "Tican Services Kubernetes Engine"
  SPRING.PROFILES.ACTIVE              : "k8s"
  spring.profiles.active              : "k8s"
  PROFILE_ACTIVE                      : "k8s"
  API_LOGGING_LEVEL                   : "trace"
  API_SWAGGER_ENABLE                  : "true"
  API_JPA_SHOW_SQL                    : "true"
  API_HIBERNATE_DDL_AUTO              : "none"
  
  # Discovery Services Settings
  DISCOVERY_SERVICES_APP_NAME          : "tican-discovery-services"
  DISCOVERY_SERVICES_POD               : "tican-discovery-services-pod"
  DISCOVERY_SERVICES_CONTAINER         : "tican-discovery-services-container"
  DISCOVERY_SERVICES_REPLICAS          : "1"
  DISCOVERY_SERVICES_CLUSTERIP_SVC     : "tican-discovery-services-svc"
  DISCOVERY_SERVICES_INTERNAL_PORT     : "3000"
  DISCOVERY_SERVICES_EXPOSE_PORT       : "3000"

  # API Gateway Settings
  API_GATEWAY_APP_NAME                : "tican-api-gateway"
  API_GATEWAY_POD                     : "api-gateway-pod"
  API_GATEWAY_CONTAINER               : "api-gateway-container"
  API_GATEWAY_REPLICAS                : "1"
  API_GATEWAY_CLUSTERIP_SVC           : "api-gateway-svc"
  API_GATEWAY_INTERNAL_PORT           : "3001"
  API_GATEWAY_EXPOSE_PORT             : "3001"

  # Authentication Server Settings  
  AUTHENTICATION_SERVER_APP_NAME      : "tican-authentication-server"
  AUTHENTICATION_SERVER_POD           : "tican-authentication-server-pod"
  AUTHENTICATION_SERVER_CONTAINER     : "tican-authentication-server-container"
  AUTHENTICATION_SERVER_REPLICAS      : "1"
  AUTHENTICATION_SERVER_CLUSTERIP_SVC : "tican-authentication-server-svc"
  AUTHENTICATION_SERVER_INTERNAL_PORT : "0" #"6002"
  AUTHENTICATION_SERVER_EXPOSE_PORT   : "31002"
  
  # Authenticantion Server JKS Settings
  AUTH_JKS_KEYPASS                    : "123456"
  AUTH_JKS_STOREPASS                  : "123456"
  AUTH_JKS_ALIAS                      : "tican"
  AUTH_JKS_PATH                       : "keystore/tican.jks"
    
  # OAuth2 Clients Domain Settings
  OAUTH2_CLIENTS_DOMAIN_APP_NAME      : "oauth2-clients-domain-api"
  OAUTH2_CLIENTS_DOMAIN_POD           : "oauth2-clients-domain-pod"
  OAUTH2_CLIENTS_DOMAIN_CONTAINER     : "oauth2-clients-domain-container"
  OAUTH2_CLIENTS_DOMAIN_REPLICAS      : "1"
  OAUTH2_CLIENTS_DOMAIN_CLUSTERIP_SVC : "oauth2-clients-domain-svc"
  OAUTH2_CLIENTS_DOMAIN_INTERNAL_PORT : "0" #"6003"
  OAUTH2_CLIENTS_DOMAIN_EXPOSE_PORT   : "31003"

  # OAuth2 Clients Business Settings
  OAUTH2_CLIENTS_BUSINESS_APP_NAME      : "oauth2-clients-business-api"
  OAUTH2_CLIENTS_BUSINESS_POD           : "oauth2-clients-business-pod"
  OAUTH2_CLIENTS_BUSINESS_CONTAINER     : "oauth2-clients-business-container"
  OAUTH2_CLIENTS_BUSINESS_REPLICAS      : "1"
  OAUTH2_CLIENTS_BUSINESS_CLUSTERIP_SVC : "oauth2-clients-business-svc"
  OAUTH2_CLIENTS_BUSINESS_INTERNAL_PORT : "0" #"6004"
  OAUTH2_CLIENTS_BUSINESS_EXPOSE_PORT   : "31004"
  
  # OAuth2 Users Domain Settings
  OAUTH2_USERS_DOMAIN_APP_NAME          : "oauth2-users-domain-api"
  OAUTH2_USERS_DOMAIN_POD               : "oauth2-users-domain-pod"
  OAUTH2_USERS_DOMAIN_CONTAINER         : "oauth2-users-domain-container"
  OAUTH2_USERS_DOMAIN_REPLICAS          : "1"
  OAUTH2_USERS_DOMAIN_CLUSTERIP_SVC     : "oauth2-users-domain-svc"
  OAUTH2_USERS_DOMAIN_INTERNAL_PORT     : "0" #"6005"
  OAUTH2_USERS_DOMAIN_EXPOSE_PORT       : "31005"
  
  # OAuth2 Users Business Settings
  OAUTH2_USERS_BUSINESS_APP_NAME        : "oauth2-users-business-api"
  OAUTH2_USERS_BUSINESS_POD             : "oauth2-users-business-pod"
  OAUTH2_USERS_BUSINESS_CONTAINER       : "oauth2-users-business-container"
  OAUTH2_USERS_BUSINESS_REPLICAS        : "1"
  OAUTH2_USERS_BUSINESS_CLUSTERIP_SVC   : "oauth2-users-business-svc"
  OAUTH2_USERS_BUSINESS_INTERNAL_PORT   : "0" #"6006"
  OAUTH2_USERS_BUSINESS_EXPOSE_PORT     : "31006"

  # Audit Services Settings
  AUDIT_SERVICES_APP_NAME      : "audit-services"
  AUDIT_SERVICES_POD           : "audit-services-pod"
  AUDIT_SERVICES_CONTAINER     : "audit-services-container"
  AUDIT_SERVICES_REPLICAS      : "1"
  AUDIT_SERVICES_CLUSTERIP_SVC : "audit-services-svc"
  AUDIT_SERVICES_INTERNAL_PORT : "0" #"6011"
  AUDIT_SERVICES_EXPOSE_PORT   : "31011"
  
  # MySQL Services Settings                                      
  MYSQL_POD                           : "db-mysql-pod"
  MYSQL_CONTAINER                     : "db-mysql-container"
  MYSQL_REPLICAS                      : "1"
  MYSQL_CLUSTERIP_SVC                 : "db-mysql-svc"
  MYSQL_INTERNAL_PORT                 : "3306"
  MYSQL_EXPOSE_PORT                   : "31306"
  MYSQL_DATABASE                      : "user"
  MYSQL_ROOT_PASSWORD                 : root
  
  # Oracle Services Services
  ORACLEXE_POD                        : "db-oracle-pod"
  ORACLEXE_CONTAINER                  : "db-oracle-container"
  ORACLEXE_REPLICAS                   : "1"
  ORACLEXE_CLUSTERIP_SVC              : "db-oracle-svc"
  ORACLE_INTERNAL_PORT                : "1521"
  ORACLE_EXPOSE_PORT                  : "31521"
  ORACLE_SID                          : "XE"
  ORACLE_USER                         : "sys"
  ORACLE_PWD                          : "tican"
  ORACLE_PASSWORD                     : "tican"
  ORACLE_TICAN_USER                   : "tican2_user"
  ORACLE_TICAN_USER_PWD               : "tican"
 
  # RabbitMQ Services Settings
  RABBITMQ_POD                        : "mq-rabbit-pod"
  RABBITMQ_CONTAINER                  : "mq-rabbit-container"
  RABBITMQ_REPLICAS                   : "1"
  RABBITMQ_CLUSTERIP_SVC              : "mq-rabbit-services-0"
  RABBITMQ_SERVICE_INTERNAL_PORT      : "5672"
  RABBITMQ_CLUSTER_INTERNAL_PORT      : "5673"
  RABBITMQ_DASHBOARD_INTERNAL_PORT    : "15672"
  RABBITMQ_SERVICE_EXPOSE_PORT        : "0"
  RABBITMQ_CLUSTER_EXPOSE_PORT        : "0"
  RABBITMQ_DASHBOARD_EXPOSE_PORT      : "32672"
  RABBITMQ_DEFAULT_USER               : "tican"
  RABBITMQ_DEFAULT_PASS               : "tican"
  
  # RabbitMQ Services AMQP settings
  API_AMQP_AUDIT_QUEUE                : "tican.audit.queue"
  API_AMQP_AUDIT_EX                   : "tican.audit.ex"
  API_AMQP_AUDIT_DLQ                  : "tican.audit.dlq"
  API_AMQP_AUDIT_DLX                  : "tican.audit.dlx"
  