apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tican-discovery-services
  labels:
    app: tican-discovery-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tican-discovery-services-pod
  template:
    metadata:
      name: tican-discovery-services-pod
      labels:
        app: tican-discovery-services-pod
    spec:
      containers:
        - name: tican-discovery-services-container
          image: fras200627/tican-discovery-services:1.0.0-openapi
          ports:
            - containerPort: 3000
              name: discovery-services-pod
          envFrom:
            - configMapRef:
                name: config-map-defaults              
            - configMapRef:
                name: tican-discovery-services-cmap  
          volumeMounts:
            - name: tican-discovery-services-persist
              mountPath: /default/tican-discovery-services-pvc
      restartPolicy: Always
#      restartPolicy: OnFailure
#      restartPolicy: Never
      volumes:
        - name: tican-discovery-services-persist
          persistentVolumeClaim:
            claimName: tican-discovery-services-pvc
  serviceName: tican-discovery-services-stateful
    