# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: tican-eureka-cmap
  labels:
    app: tican-eureka-cmap
data:
  SPRING.PROFILES.ACTIVE        : "dev"
  SERVICE_DISCOVERY_EXPOSE_PORT : "31080"
  PROFILE_ACTIVE                : "dev"
  API_LOGGING_LEVEL             : "trace"

