apiVersion: v1
kind: Service
metadata:
  name: oauth2-clients-business-svc
  labels:
    app: oauth2-clients-business-svc
spec:
  type: ClusterIP
  selector:
    app: oauth2-clients-business-pod
  ports:
    - port: 6004
      targetPort: 6004
