apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-clients-domain-cmap
  labels:
    app: oauth2-clients-domain-cmap
data:
  API_LOGGING_LEVEL              : "error"
  API_SWAGGER_ENABLE             : "false"
  OAUTH2_CLIENTS_DOMAIN_REPLICAS : "1"
  
