apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discovery-services-pvc
  labels:
    app: discovery-services-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
      
