# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-mysql-cmap
  labels:
    app: db-mysql-cmap
data:
  MYSQL_IMAGE         : 'fras200627/db-tican-mysql:210.0'
  MYSQL_DATABASE      : 'user'
  MYSQL_HOST_NAME     : 'db-mysql-pod'
  MYSQL_ROOT_PASSWORD : 'root'
  MYSQL_USER          : 'tican'
  MYSQL_PASSWORD      : 'root'
  MYSQL_INTERNAL_PORT : '3306'
  MYSQL_EXPOSE_PORT   : '3306'
  API_JPA_SHOW_SQL    : 'true'
  API_HIBERNATE_DDL_AUTO: 'none'
  MYSQL_DATA_VOLUME     : '/opt/containerd/volume-docker/mysql/mysqldata'
  MYSQL_BACKUP_VOLUME   : '/opt/containerd/volume-docker/mysql/mysqlbackup'

