# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: db-oracle-nodeport
  labels:
    app: db-oracle-nodeport
spec:
  type: NodePort
  ports:
    - port: 1521
      nodePort: 31521
  selector:
    app: db-oracle-pod
