# ---------------------------------------------------------------
# ---------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: tican-eureka-svc
  labels:
    app: tican-eureka-svc
spec:
  type: ClusterIP
  selector:
    app: tican-eureka-pod
  ports:
    - port: 5000
      targetPort: 5000
      
    
  