apiVersion: v1
kind: Service
metadata:
  name: mq-rabbit-svc
  labels:
    app: mq-rabbit-svc
spec:
  type: ClusterIP
  clusterIP: 10.152.183.203
  selector:
    app: mq-rabbit-pod
  ports:
    - port: 5672
      targetPort: 31672
      name: svc-port
    - port: 5673
      targetPort: 31673
      name: cluster-port
    - port: 15672
      targetPort: 32672
      name: dashboard-port
  