apiVersion: v1
kind: Service
metadata:
  name: oauth2-clients-business-nodeport
  labels:
    app: oauth2-clients-business-nodeport
spec:
  type: NodePort
  ports:
    - port: 6004
      nodePort: 31004
  selector:
    app: oauth2-clients-business-pod
